# Code Generation Evaluation Configuration
eval:
  metric: "pass@k"
  num_tests_per_prompt: 5
  seed: 42
  k_value: 1
  save_path: null

generation:
  backend: "vllm"
  max_new_tokens: ${generation.vllm_cfg.max_model_len}
  temperature: 0.2
  top_p: 1.0
  top_k: -1
  num_prompts_per_step: -1
  model_name: "Qwen/Qwen2.5-Coder-1.5B-Instruct"
  stop_token_ids: null
  stop_strings: null
  vllm_cfg:
    async_engine: false
    precision: "bfloat16"
    tensor_parallel_size: 1
    pipeline_parallel_size: 1
    expert_parallel_size: 1
    gpu_memory_utilization: 0.9
    max_model_len: 4096
    enforce_eager: False
  colocated:
    enabled: true
    resources:
      gpus_per_node: null
      num_nodes: null

tokenizer:
  name: ${generation.model_name}
  chat_template: "default"
  chat_template_kwargs: null

data:
  max_input_seq_length: ${generation.vllm_cfg.max_model_len}
  prompt_file: "examples/prompts/code.txt"
  system_prompt_file: null
  dataset_name: "livecodebench"
  env_name: "code_test"

env:
  code_test:
    num_workers: 8
    timeout_per_test: 10

cluster:
  gpus_per_node: 1
  num_nodes: 1
