# Math evaluation Configuration
defaults: "gpqa_eval.yaml"

data:
  prompt_file: "examples/prompts/cot.txt"
  dataset_name: "ifeval"

env:
  math:
    verifier_type: "instruction_following"
    verifier_metadata_key: "checker_info"
