# Math evaluation Configuration
defaults: "gpqa_eval.yaml"

generation:
  model_name: "Qwen/Qwen2.5-7B-Instruct"
  skip_special_tokens: false

data:
  prompt_file: "examples/prompts/cot.txt"
  dataset_name: "math"

env:
  math:
    verifier_type: "math"
    verifier_metadata_key: "ground_truth"
