# Math evaluation Configuration
defaults: "gpqa_eval.yaml"

generation:
  vllm_cfg:
    max_model_len: 4096

data:
  prompt_file: "examples/prompts/mbpp.txt"
  dataset_name: "mbpp"

env:
  math:
    verifier_type: "code"
    verifier_metadata_key: "tests"
