 # Set the language for reviews by using the corresponding ISO language code.
 # Default: "en-US"
 language: en-US
 # Set the tone of reviews and chat.
 # Default: ""
 tone_instructions: '' # not in base
 # Enable early-access features.
 # Default: false
 early_access: false # not in base
 # Enable free tier features for users not on a paid plan.
 # Default: true
 enable_free_tier: true # not in base
 tone_instructions: ''
 early_access: false
 enable_free_tier: true
 # Settings related to reviews.
 # Default: {}
 reviews:
  profile: chill
  # Set the profile for reviews. Assertive profile yields more feedback, that may be considered nitpicky.
  # Options: chill, assertive
  # Default: "chill"
  request_changes_workflow: false # not in base
  # Approve the review once CodeRabbit’s comments are resolved and no pre-merge checks are in an error state.
  # Default: false
  high_level_summary: true # not in base
  # Generate a high level summary of the changes in the PR/MR description.
  # Default: true
  high_level_summary_placeholder: '@coderabbitai summary' # not in base
  # Placeholder in the PR/MR description that gets replaced with the high level summary.
  # Default: "@coderabbitai summary"
  high_level_summary_in_walkthrough: false # not in base
  # Include the high level summary in the walkthrough comment.
  # Default: false
  auto_title_placeholder: '@coderabbitai'
  # Add this keyword in the PR/MR title to auto-generate the title.
  # Default: "@coderabbitai"
  auto_title_instructions: ''
  # Auto Title Instructions - Custom instructions for auto-generating the PR/MR title.
  # Default: ""
  review_status: true
  # Post review details on each review. Additionally, post a review status when a review is skipped in certain cases.
  # Default: true
  commit_status: true
  # Set the commit status to 'pending' when the review is in progress and 'success' when it is complete.
  # Default: true
  fail_commit_status: false
  # Set the commit status to 'failure' when the PR cannot be reviewed by CodeRabbit for any reason.
  # Default: false
  collapse_walkthrough: false
  # Generate walkthrough in a markdown collapsible section.
  # Default: false
  changed_files_summary: true # not in base
  # Generate a summary of the changed files in the walkthrough.
  # Default: true
  sequence_diagrams: true # not in base
  # Generate sequence diagrams in the walkthrough.
  # Default: true
  estimate_code_review_effort: true # not in base
  # Estimate the code review effort in the walkthrough.
  # Default: true
  assess_linked_issues: true
  # Generate an assessment of how well the changes address the linked issues in the walkthrough.
  # Default: true
  related_issues: true
  # Include possibly related issues in the walkthrough.
  # Default: true
  related_prs: true
  # Related PRs - Include possibly related pull requests in the walkthrough.
  # Default: true
  suggested_labels: true
  # Suggest labels based on the changes in the pull request in the walkthrough.
  # Default: true
  auto_apply_labels: false # not in base
  # Automatically apply the suggested labels to the PR/MR.
  # Default: false
  suggested_reviewers: true
  # Suggest reviewers based on the changes in the pull request in the walkthrough.
  # Default: true
  auto_assign_reviewers: false # not in base
  # Automatically assign suggested reviewers to the pull request
  # Default: false
  poem: true
  # Generate a poem in the walkthrough comment.
  # Default: true
  labeling_instructions: [] # not in base
  # Labeling Instructions - Provide guidelines for suggesting labels for the PR/MR.
  # Default: []
  path_filters: [] # not in base
  # Specify file patterns to include or exclude in a review using glob patterns.
  # Default: []
  path_instructions: [] # not in base
  # Path Instructions - Provide specific additional guidelines for code review based on file paths.
  # Default: []
  abort_on_close: true # not in base
  # Abort the in-progress review if the pull request is closed or merged.
  # Default: true
  disable_cache: false # not in base
  # Disable caching of code and dependencies.
  # Default: false
  auto_review:
    # Configuration for auto review
    # Default: {}
    enabled: true # not in base
    # Automatic Review - Automatic code review
    # Default: true
    auto_incremental_review: true
    # Automatic Incremental Review - Automatic incremental code review on each push
    # Default: true
    ignore_title_keywords: [] # not in base
    # Ignore reviewing if the title of the pull request contains any of these keywords.
    # Default: []
    labels: [] # not in base
    # List of labels to control which PRs/MRs to review.
    # Default: []
    drafts: false
    # Review draft PRs/MRs.
    # Default: false
    base_branches: []
    # Base branches (other than the default branch) to review. Accepts regex patterns.
    # Default: []
    ignore_usernames: [] # not in base
    # Ignore reviewing pull requests by these usernames.
    # Default: []
  finishing_touches: # not in base
    # Configuration for finishing touches
    # Default: {}
    docstrings:
      # Docstrings - Allow CodeRabbit to generate docstrings for PRs/MRs.
      # Default: true
      enabled: true
    unit_tests:
      # Unit Tests - Allow CodeRabbit to generate unit tests for PRs/MRs.
      # Default: true
      enabled: true
  pre_merge_checks: # not in base
    # Configuration for pre merge checks
    # Default: {}
    docstrings:
      # Mode - Determines how strictly the docstring coverage check is enforced.
      # Default: "warning"
      mode: warning
      # Percentage threshold for docstring coverage check.
      # Default: 80
      threshold: 80
    title:
      # Mode - Determines how strictly the title check is enforced.
      # Default: "warning"
      mode: warning
      # Requirements - Requirements for the pull request title.
      # Default: ""
      requirements: ''
    description:
      # Mode - Determines how strictly the description check is enforced.
      # Default: "warning"
      mode: warning
    issue_assessment:
      # Mode - Determines how strictly the issue assessment check is enforced.
      # Default: "warning"
      mode: warning
    custom_checks: []
    # Custom Pre-merge Checks - Add unique checks to enforce your team's standards before merging a pull request.
    # Default: []
  tools: # not in base
    # Tools that provide additional context to code reviews.
    # Default: {}
    ast-grep:
      # List of rules directories.
      # Default: []
      rule_dirs: []
      # List of utils directories.
      # Default: []
      util_dirs: []
      # Use ast-grep essentials package.
      # Default: true
      essential_rules: true
      # Predefined packages to be used.
      # Default: []
      packages: []
    shellcheck:
      # Enable ShellCheck - Enable ShellCheck integration.
      # Default: true
      enabled: true
    ruff:
      # Enable Ruff - Enable Ruff integration.
      # Default: true
      enabled: true
    markdownlint:
      # Enable markdownlint - Enable markdownlint integration.
      # Default: true
      enabled: true
    github-checks:
      # Enable GitHub Checks - Enable GitHub Checks integration.
      # Default: true
      enabled: true
      # Time in milliseconds to wait for all GitHub Checks to conclude.
      # Default: 90000
      timeout_ms: 90000
    languagetool:
      # Enable LanguageTool - Enable LanguageTool integration.
      # Default: true
      enabled: true
      # IDs of rules to be enabled.
      # Default: []
      enabled_rules: []
      # IDs of rules to be disabled.
      # Default: []
      disabled_rules: []
      # IDs of categories to be enabled.
      # Default: []
      enabled_categories: []
      # IDs of categories to be disabled.
      # Default: []
      disabled_categories: []
      # Only the rules and categories whose IDs are specified are enabled.
      # Default: false
      enabled_only: false
      # Level of strictness for LanguageTool.
      # Default: "default"
      level: default
    biome:
      # Enable Biome - Enable Biome integration.
      # Default: true
      enabled: true
    hadolint:
      # Enable Hadolint - Enable Hadolint integration.
      # Default: true
      enabled: true
    swiftlint:
      # Enable SwiftLint - Enable SwiftLint integration.
      # Default: true
      enabled: true
    phpstan:
      # Enable PHPStan - Enable PHPStan integration.
      # Default: true
      enabled: true
      # Level - Specify the rule level to run.
      # Default: "default"
      level: default
    phpmd:
      # Enable PHPMD - Enable PHPMD integration.
      # Default: true
      enabled: true
    phpcs:
      # Enable PHP CodeSniffer - Enable PHP CodeSniffer integration.
      # Default: true
      enabled: true
    golangci-lint:
      # Enable golangci-lint - Enable golangci-lint integration.
      # Default: true
      enabled: true
    yamllint:
      # Enable YAMLlint - Enable YAMLlint integration.
      # Default: true
      enabled: true
    gitleaks:
      # Enable Gitleaks - Enable Gitleaks integration.
      # Default: true
      enabled: true
    checkov:
      # Enable Checkov - Enable Checkov integration.
      # Default: true
      enabled: true
    detekt:
      # Enable detekt - Enable detekt integration.
      # Default: true
      enabled: true
    eslint:
      # Enable ESLint - Enable ESLint integration.
      # Default: true
      enabled: true
    flake8:
      # Enable Flake8 - Enable Flake8 integration.
      # Default: true
      enabled: true
    rubocop:
      # Enable RuboCop - Enable RuboCop integration.
      # Default: true
      enabled: true
    buf:
      # Enable Buf - Enable Buf integration.
      # Default: true
      enabled: true
    regal:
      # Enable Regal - Enable Regal integration.
      # Default: true
      enabled: true
    actionlint:
      # Enable actionlint - Enable actionlint integration.
      # Default: true
      enabled: true
    pmd:
      # Enable PMD - Enable PMD integration.
      # Default: true
      enabled: true
    cppcheck:
      # Enable Cppcheck - Enable Cppcheck integration.
      # Default: true
      enabled: true
    semgrep:
      # Enable Semgrep - Enable Semgrep integration.
      # Default: true
      enabled: true
    circleci:
      # Enable CircleCI - Enable CircleCI integration.
      # Default: true
      enabled: true
    clippy:
      # Enable Clippy - Enable Clippy integration.
      # Default: true
      enabled: true
    sqlfluff:
      # Enable SQLFluff - Enable SQLFluff integration.
      # Default: true
      enabled: true
    prismaLint:
      # Enable Prisma Schema linting
      # Default: true
      enabled: true
    pylint:
      # Enable Pylint - Enable Pylint integration.
      # Default: true
      enabled: true
    oxc:
      # Enable Oxlint - Enable Oxlint integration.
      # Default: true
      enabled: true
    shopifyThemeCheck:
      # Enable Shopify Theme Check
      # Default: true
      enabled: true
    luacheck:
      # Enable Lua code linting - Enable Luacheck integration.
      # Default: true
      enabled: true
    brakeman:
      # Enable Brakeman - Enable Brakeman integration.
      # Default: true
      enabled: true
    dotenvLint:
      # Enable dotenv-linter - Enable dotenv-linter integration.
      # Default: true
      enabled: true
    htmlhint:
      # Enable HTMLHint - Enable HTMLHint integration.
      # Default: true
      enabled: true
    checkmake:
      # Enable checkmake - Enable checkmake integration.
      # Default: true
      enabled: true
    osvScanner:
      # Enable OSV Scanner - Enable OSV Scanner integration.
      # Default: true
      enabled: true
 # Configuration for chat
 # Default: {}
 chat: # not in base
  art: true
  # Generate art in response to chat messages.
  # Default: true
  auto_reply: true
  # Enable the bot to reply automatically without requiring the user to tag it.
  # Default: true
  integrations:
    # Configuration for integrations
    # Default: {}
    jira:
      # Jira - Enable the Jira integration for opening issues, etc.
      # Default: "auto"
      usage: auto
    linear:
      # Linear - Enable the Linear integration for opening issues, etc.
      # Default: "auto"
      usage: auto
knowledge_base:
  # Configuration for knowledge base
  # Default: {}
  opt_out: false # not in base
  # Opt Out - Disable all knowledge base features that require data retention.
  # Default: false
  web_search:
    # Configuration for web search
    # Default: {}
    enabled: true # not in base
    # Web Search - Enable the web search integration.
    # Default: true
  code_guidelines:
    enabled: true
    # CodeRabbit will analyse and learn from your organization's code guidelines.
    # Default: {}
    filePatterns: []
    # File Patterns - Specify files for your coding guideline documents.
    # Default: []
  learnings:
    # Configuration for learnings
    # Default: {}
    scope: auto # not in base
    # Learnings - Specify the scope of learnings to use for the knowledge base.
    # Default: "auto"
  issues:
    # Configuration for issues
    # Default: {}
    scope: auto # not in base
    # Issues - Specify the scope of git platform issues to use for the knowledge base.
    # Default: "auto"
  jira:
    # Configuration for jira
    # Default: {}
    usage: auto # not in base
    # Jira - Enable the Jira knowledge base integration.
    # Default: "auto"
    project_keys: [] # not in base
    # Jira Project Keys - Specify the Jira project keys to use for the knowledge base.
    # Default: []
  linear:
    # Configuration for linear
    # Default: {}
    usage: auto # not in base
    # Linear - Enable the Linear knowledge base integration.
    # Default: "auto"
    team_keys: [] # not in base
    # Linear Team Keys - Specify the Linear team keys to use for the knowledge base.
    # Default: []
  pull_requests:
    # Configuration for pull requests
    # Default: {}
    scope: auto # not in base
    # Pull Requests - Specify the scope of pull requests to use for the knowledge base.
    # Default: "auto"
  mcp:
    # Configuration for mcp
    # Default: {}
    usage: auto # not in base
    # MCP - Enable the MCP knowledge base integration.
    # Default: "auto"
    disabled_servers: [] # not in base
    # MCP Disabled Servers - Specify MCP server labels to disable.
    # Default: []
code_generation: # not in base
  # Configuration for code generation
  # Default: {}
  docstrings:
    # Settings related to the generation of docstrings.
    # Default: {"path_instructions":[]}
    language: en-US # not in base
    # Set the language for docstrings by using the corresponding ISO language code.
    # Default: "en-US"
    path_instructions: [] # not in base
    # Path Instructions - Provide additional guidelines for docstring generation based on file paths.
    # Default: []
  unit_tests:
    # Settings related to the generation of unit tests.
    # Default: {"path_instructions":[]}
    path_instructions: [] # not in base
    # Unit Test Generation - Provide additional guidelines for unit test generation based on file paths.
    # Default: []