[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nemo-reinforcer"
dynamic = [
    "version",
    "readme",
]
description = "Nemo-Reinforcer: A Scalable and Efficient Post-Training Library for Models Ranging from 1 GPU to 1000s, and from Tiny to >100B Parameters"
requires-python = ">=3.10"
license = {text = "Apache 2.0"}
dependencies = [
    "torch==2.6.0",
    "colored==2.2.3",
    "ray[default]==2.43.0",
    "transformers",
    "wandb",
    "numpy",
    "datasets",
    "rich",
    "math-verify",
    "accelerate>=0.26",
    "tensorboard",
    "omegaconf",
    "torchdata",
    "vllm==0.8.0",
    "nvidia-ml-py",
    "hydra-core",
]

[tool.setuptools]
packages = ["nemo_reinforcer"]

[tool.setuptools.dynamic]
version = {attr = "nemo_reinforcer.__version__"}  # any module attribute compatible with ast.literal_eval
readme = {file = "README.md", content-type = "text/markdown"}

[dependency-groups]
build = [
    "torch==2.6.0",
    "setuptools",
    "packaging",
    "einops"
]
docs = [
    "sphinx",
    "sphinx-autobuild",  # For live doc serving while editing docs
    "sphinx-autodoc2",  # For documenting Python API
    "sphinx-copybutton",  # Adds a copy button for code blocks
    "myst_parser",  # For our markdown docs
    "nvidia-sphinx-theme",  # Our NVIDIA theme
]
dev = [
    "pre-commit==3.6.0",
    "ruff==0.9.9",
]
test = [
    "pytest>=7.0.0",
    "pytest-timeout",
    "pytest-cov",
]


[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | build
)/
'''

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"

[tool.ruff.lint]
# Enable all `pydocstyle` rules, limiting to those that adhere to the
# Google convention via `convention = "google"`, below.
select = ["D"]

# On top of the Google convention, disable `D417`, which requires
# documentation for every function parameter.
# TODO: Remove D10 once we are about to release to get all the docstrings written
ignore = ["D417", "D10"]

[tool.ruff.lint.pydocstyle]
convention = "google"

# Section to exclude errors for different file types
[tool.ruff.per-file-ignores]
# Ignore all directories named `tests`.
"tests/**" = ["D"]
# Ignore all files that end in `_test.py`.
"*_test.py" = ["D"]
