python-version = "3.13.13"
replace-imports-with-any = [
  "nemo_automodel.*",
  "pynvml.*",
  "hydra._internal.*",
  "hydra.core.override_parser.*",
  "datasets.*",
  "transformers.*",
  "vllm.*",
  "math_verify.*",
  "sympy.*",
  "torchdata.*",
  "nemo.*",
  "megatron.*",
  "ray.*",
  "numpy.*",
  "sphinx.*",
  "docutils.*",
]
project-includes = [
  "nemo_rl/**/*.py",
  "examples/**/*.py",
  "docs/*.py",
  "tools/**/*.py",
]

# Disable TypedDict mutation errors since TypedDict objects are regular dicts at runtime
[errors]
missing-attribute = false
