defaults: ../../grpo_math_qwen30ba3b_megatron.yaml
grpo:
  num_prompts_per_step: 32
  num_generations_per_prompt: 16
  max_num_steps: 10
  val_at_start: true
  val_at_end: true
  max_val_samples: 128
  val_batch_size: 128
  async_grpo:
    enabled: true
    in_flight_weight_updates: true
policy:
  train_global_batch_size: 32
  logprob_batch_size: 1
  sequence_packing:
    enabled: true
  megatron_cfg:
    attention_backend: flash
    scheduler:
      lr_decay_iters: 500
      lr_warmup_iters: 10
  generation:
    vllm_cfg:
      async_engine: true
      env_vars:
        VLLM_USE_FLASHINFER_MOE_FP16: '0'
        VLLM_USE_FLASHINFER_MOE_FP8: '0'
    colocated:
      enabled: false
      resources:
        num_nodes: 1
        gpus_per_node: 8
loss_fn:
  reference_policy_kl_penalty: 0.0
  ratio_clip_min: 1.0
  ratio_clip_max: 5.0
  use_importance_sampling_correction: true
  use_cispo: true
logger:
  log_dir: logs/cispo-mm1-async-lag1-highoffpolicy-qwen3-30ba3b-3n8g-megatron-cispo
  wandb_enabled: true
  tensorboard_enabled: true
  wandb:
    project: nemo-rl
    name: cispo-mm1-async-lag1-highoffpolicy-qwen3-30ba3b-3n8g-megatron-cispo
cluster:
  num_nodes: 3
