defaults: ../../grpo_math_1B.yaml
grpo:
  num_prompts_per_step: 2
  num_generations_per_prompt: 8
  val_period: -1
checkpointing:
  checkpoint_dir: results/grpo-qwen3.8-27b-2n8g-megatron
policy:
  model_name: Qwen/Qwen3.8-27B
  train_global_batch_size: 16
  train_micro_batch_size: 1
  logprob_batch_size: 1
  make_sequence_length_divisible_by: 4
  dtensor_cfg:
    enabled: false
  megatron_cfg:
    enabled: true
    tensor_model_parallel_size: 4
    sequence_parallel: true
    apply_rope_fusion: false
    activation_checkpointing: true
    defer_fp32_logits: true
  sequence_packing:
    enabled: false
  dynamic_batching:
    enabled: true
  generation:
    max_new_tokens: 256
    vllm_cfg:
      tensor_parallel_size: 8
      max_model_len: 512
      gpu_memory_utilization: 0.7
      enforce_eager: true
data:
  max_input_seq_length: 256
logger:
  wandb_enabled: true
  tensorboard_enabled: true
  wandb:
    project: nemo-rl
    name: grpo-qwen3.8-27b-2n8g-megatron
cluster:
  gpus_per_node: 8
  num_nodes: 2
