defaults: ./grpo-moonlight-16ba3b-4n8g-megatron.yaml
grpo:
  async_grpo:
    enabled: true
    in_flight_weight_updates: true
loss_fn:
  use_importance_sampling_correction: true
policy:
  generation:
    colocated:
      enabled: false
      resources:
        num_nodes: 2
        gpus_per_node: 8
    vllm_cfg:
      expert_parallel_size: 8
logger:
  wandb:
    name: grpo-moonlight-16ba3b-4n8g-megatron-vllm-dp-async
