defaults: grpo-qwen3.5-9b-1n8g-megatron.yaml
grpo:
  num_prompts_per_step: 32
  num_generations_per_prompt: 8
checkpointing:
  checkpoint_dir: results/grpo-qwen3.8-27b-2n8g-megatron-tp2pp2cp2
policy:
  model_name: Qwen/Qwen3.8-27B
  train_global_batch_size: 256
  dynamic_batching:
    enabled: false
  sequence_packing:
    enabled: true
  make_sequence_length_divisible_by: 8
  megatron_cfg:
    tensor_model_parallel_size: 2
    pipeline_model_parallel_size: 2
    context_parallel_size: 2
  generation:
    vllm_cfg:
      tensor_parallel_size: 4
logger:
  wandb:
    name: grpo-qwen3.8-27b-2n8g-megatron-tp2pp2cp2
cluster:
  gpus_per_node: 8
  num_nodes: 2
