defaults: ../../grpo_math_qwen30ba3b_megatron.yaml
grpo:
  max_num_steps: 5
  num_prompts_per_step: 8
  num_generations_per_prompt: 4
checkpointing:
  checkpoint_dir: results/grpo-qwen3-30ba3b-2n4g-megatron_generation-noncolocated-zero-kl
policy:
  train_global_batch_size: 32
  max_total_sequence_length: 2048
  megatron_cfg:
    zero_train_gen_mismatch: true
    moe_permute_fusion: false
    tensor_model_parallel_size: 1
    expert_model_parallel_size: 4
    moe_router_dtype: fp32
    defer_fp32_logits: true
    activation_checkpointing: true
  generation:
    backend: megatron
    refit_transport: mcore
    colocated:
      enabled: false
      resources:
        gpus_per_node: ${cluster.gpus_per_node}
        num_nodes: 1
    mcore_generation_config:
      transformer_impl: inference_optimized
      moe_router_dtype: fp32
      logprobs_mode: raw_logprobs
      enable_chunked_prefill: false
      inference_grouped_gemm_backend: vllm
      inference_moe_token_dispatcher_type: nvls
      refit_backend: nccl
      num_cuda_graphs: -1
      moe_pad_experts_for_cuda_graph_inference: false
cluster:
  gpus_per_node: 4
  num_nodes: 2
logger:
  log_dir: logs/grpo-qwen3-30ba3b-2n4g-megatron_generation-noncolocated-zero-kl
  wandb:
    name: grpo-qwen3-30ba3b-2n4g-megatron_generation-noncolocated-zero-kl
