defaults: ../../grpo_math_1B.yaml
grpo:
  num_prompts_per_step: 1
  num_generations_per_prompt: 8
checkpointing:
  checkpoint_dir: results/grpo-nanov3-toy
policy:
  model_name: /data/toy_models/nemotron-nano-toy-model
  tokenizer:
    name: ${policy.model_name}
  train_global_batch_size: 8
  train_micro_batch_size: 1
  logprob_batch_size: 1
  max_total_sequence_length: 512
  dtensor_cfg:
    enabled: false
  megatron_cfg:
    enabled: true
    bias_activation_fusion: false
    tensor_model_parallel_size: 4
    expert_model_parallel_size: 1
    pipeline_model_parallel_size: 1
    sequence_parallel: true
    peft:
      enabled: false
  sequence_packing:
    enabled: false
  generation:
    backend: megatron
    mcore_generation_config:
      buffer_size_gb: 4  # Total buffer size is 2x this value (active requests + paused requests)
      num_cuda_graphs: null  # Number of CUDA graphs to pre-compile for different batch sizes
      block_size_tokens: 256  # Size of each KV cache block in tokens (affects memory granularity)
      use_cuda_graphs_for_non_decode_steps: true  # Enable CUDA graphs for prefill/context processing
      enable_chunked_prefill: null  # Split long prefills into chunks for better memory management
      unified_memory_level: 0  # Unified memory usage level (0=disabled, higher values enable more aggressive paging)
      max_tokens: 16384 # Maximum number of tokens to use in a single step. Analogous to vllm's max_num_batched_tokens
    vllm_cfg:
      enabled: false
      tensor_parallel_size: 4
      gpu_memory_utilization: 0.7
logger:
  wandb_enabled: true
  tensorboard_enabled: true
  wandb:
    project: nemo-rl
    name: grpo-nanov3-toy
cluster:
  gpus_per_node: 4
  num_nodes: 1
