defaults: grpo-qwen3.5-9b-1n8g-megatron.yaml
grpo:
  num_prompts_per_step: 16
  num_generations_per_prompt: 8
checkpointing:
  checkpoint_dir: results/grpo-qwen3.8-27b-2n8g-megatron
policy:
  model_name: Qwen/Qwen3.8-27B
  train_global_batch_size: 128
  make_sequence_length_divisible_by: 4
  generation:
    vllm_cfg:
      tensor_parallel_size: 8
logger:
  wandb:
    name: grpo-qwen3.8-27b-2n8g-megatron
cluster:
  num_nodes: 2
