defaults: ../../ppo_gsm8k_1.5B_megatron.yaml
value:
  make_sequence_length_divisible_by: 4
  megatron_cfg:
    context_parallel_size: 2
  sequence_packing:
    enabled: true
checkpointing:
  checkpoint_dir: results/ppo-qwen2.5-1.5b-gsm8k-1n8g-megatron-valuepack-cp2
logger:
  log_dir: logs/ppo-qwen2.5-1.5b-gsm8k-1n8g-megatron-valuepack-cp2
  wandb:
    name: ppo-qwen2.5-1.5b-gsm8k-1n8g-megatron-valuepack-cp2
