defaults: "../../sft.yaml"

sft:
  max_num_steps: 350


checkpointing:
  checkpoint_dir: results/sft-llama3.1-8b-instruct-1n8g-fsdp2tp2sp

policy:
  model_name: meta-llama/Llama-3.1-8B-Instruct
  tokenizer:
    name: meta-llama/Llama-3.1-8B-Instruct
    chat_template: '{% for message in messages %}{%- if message[''role''] == ''system''  %}{{''Context: '' + message[''content''].strip()}}{%- elif message[''role''] == ''user''  %}{{'' Question: '' + message[''content''].strip() + '' Answer:''}}{%- elif message[''role''] == ''assistant''  %}{{'' '' + message[''content''].strip()}}{%- endif %}{% endfor %}'

  dtensor_cfg:
    enabled: true
    cpu_offload: false
    sequence_parallel: true
    activation_checkpointing: false
    tensor_parallel_size: 2
    context_parallel_size: 1
    custom_parallel_plan: null


logger:
  log_dir: logs/sft-llama3.1-8b-instruct-1n8g-fsdp2tp2sp

  wandb:
    project: nemo-rl
    name: sft-llama3.1-8b-instruct-1n8g-fsdp2tp2sp

  mlflow:
    experiment_name: "sft-dev"
    run_name: sft-llama3.1-8b-instruct-1n8g-fsdp2tp2sp

cluster:
  gpus_per_node: 8
  num_nodes: 1
