defaults: ../../sft.yaml
sft:
  max_num_steps: 50
checkpointing:
  checkpoint_dir: results/sft-moonlight-16ba3b-1n8g-megatron
  save_period: 100
policy:
  model_name: moonshotai/Moonlight-16B-A3B-Instruct
  tokenizer:
    name: moonshotai/Moonlight-16B-A3B-Instruct
    chat_template: default
  train_global_batch_size: 16
  dtensor_cfg:
    enabled: false
  make_sequence_length_divisible_by: ${policy.megatron_cfg.tensor_model_parallel_size}
  optimizer: null
  megatron_cfg:
    enabled: true
    expert_model_parallel_size: 8
    apply_rope_fusion: false
    gradient_accumulation_fusion: false
    moe_enable_deepep: true
    moe_token_dispatcher_type: flex
    optimizer:
      lr: 2.0e-05
      min_lr: 1.99999e-05
      weight_decay: 0.01
    scheduler:
      lr_warmup_iters: 5
data:
  add_generation_prompt: true
  train:
    dataset_name: OpenMathInstruct-2
    output_key: generated_solution
    split: train_1M
    split_validation_size: 0.05
    seed: ${sft.seed}
  validation: null
  default:
    prompt_file: examples/prompts/math.txt
logger:
  log_dir: logs/sft-moonlight-16ba3b-1n8g-megatron
  wandb:
    project: nemo-rl
    name: sft-moonlight-16B-A3B-Instruct-1n8g
  tensorboard:
    log_dir: tb_logs-sft-moonlight-16ba3b-1n8g
cluster:
  gpus_per_node: 8
