# Copyright (c) 2026, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import shlex
from pathlib import Path

MANIFEST_PATH = Path(__file__).parents[2] / "docker" / "venv_prefetch_manifest.tsv"

_HEADER = """\
# DO NOT EDIT BY HAND
# Generated by `uv run python -m nemo_rl.utils.venv_prefetch_manifest`.
# tests/unit/utils/test_venv_prefetch_manifest.py ensures this file is not stale.
# Columns: <venv name>\t<stage>\t<uv sync extra flags>
"""


def parse_sync_extras(py_executable: str) -> list[str]:
    """Extract the ``--extra <name>`` pairs from a registry py_executable."""
    tokens = shlex.split(py_executable)
    if tokens[:2] != ["uv", "run"]:
        raise ValueError(f"not a uv py_executable: {py_executable!r}")
    extras: list[str] = []
    i = 2
    while i < len(tokens):
        token = tokens[i]
        if token == "--extra":
            extras.extend(tokens[i : i + 2])
            i += 2
        elif token == "--directory":
            i += 2
        elif token == "--locked":
            i += 1
        else:
            raise ValueError(
                f"unhandled py_executable flag {token!r} in {py_executable!r}; "
                "teach nemo_rl/utils/venv_prefetch_manifest.py how it maps to `uv sync` flags"
            )
    return extras


def build_manifest_rows() -> list[tuple[str, str, str]]:
    """Build (venv_name, stage, extras) rows for every uv-managed actor."""
    if os.environ.get("NEMO_RL_PY_EXECUTABLES_SYSTEM", "0") == "1":
        raise RuntimeError(
            "NEMO_RL_PY_EXECUTABLES_SYSTEM=1 collapses the registry to system "
            "python; unset it to generate the manifest"
        )
    # Local import — the registry transitively pulls heavy deps (ray, modelopt).
    from nemo_rl.distributed.ray_actor_environment_registry import (
        ACTOR_ENVIRONMENT_REGISTRY,
    )

    rows: list[tuple[str, str, str]] = []
    for actor_fqn, py_executable in sorted(ACTOR_ENVIRONMENT_REGISTRY.items()):
        if not py_executable.startswith("uv"):
            continue
        extras = parse_sync_extras(py_executable)
        stage = "trtllm" if "trtllm" in extras else "deps"
        rows.append((actor_fqn, stage, " ".join(extras)))
    return rows


def render_manifest() -> str:
    """Render the manifest file content."""
    lines = [_HEADER]
    for actor_fqn, stage, extras in build_manifest_rows():
        lines.append(f"{actor_fqn}\t{stage}\t{extras}\n")
    return "".join(lines)


def main() -> None:
    """Regenerate docker/venv_prefetch_manifest.tsv in place."""
    MANIFEST_PATH.write_text(render_manifest())
    print(f"wrote {MANIFEST_PATH}")


if __name__ == "__main__":
    main()
