defaults: ./grpo-llama3.1-8b-instruct-2n8g.yaml
grpo:
  async_grpo:
    enabled: true
    max_trajectory_age_steps: 1
loss_fn:
  use_importance_sampling_correction: true
checkpointing:
  checkpoint_dir: results/async-grpo-llama3.1-8b-instruct-2n8g
policy:
  generation:
    colocated:
      enabled: false
      resources:
        num_nodes: 1
        gpus_per_node: 8
    vllm_cfg:
      async_engine: true
      gpu_memory_utilization: 0.8
logger:
  log_dir: logs/async-grpo-llama3.1-8b-instruct-2n8g-1T1G
  wandb:
    name: async-grpo-llama3.1-8b-instruct-2n8g-1T1G
cluster:
  gpus_per_node: 8
  num_nodes: 2