defaults: ./grpo-qwen3-32b-4n8g.yaml
grpo:
  async_grpo:
    enabled: true
    max_trajectory_age_steps: 1
loss_fn:
  use_importance_sampling_correction: true
checkpointing:
  checkpoint_dir: results/async-grpo-qwen3-32b-8n8g
policy:
  megatron_cfg:
    tensor_model_parallel_size: 4
    pipeline_model_parallel_size: 4
    sequence_parallel: true
  generation:
    colocated:
      enabled: false
      resources:
        num_nodes: 4
        gpus_per_node: 8
    vllm_cfg:
      async_engine: true
      tensor_parallel_size: 4
      gpu_memory_utilization: 0.8
logger:
  log_dir: logs/async-grpo-qwen3-32b-8n8g-4T4G
  wandb:
    name: async-grpo-qwen3-32b-8n8g-4T4G
cluster:
  gpus_per_node: 8
  num_nodes: 8
