defaults: ./grpo-deepseek-v3-32n8g.yaml
grpo:
  async_grpo:
    enabled: true
    max_trajectory_age_steps: 1
loss_fn:
  use_importance_sampling_correction: true
checkpointing:
  checkpoint_dir: results/async-grpo-deepseek-v3-64n8g
policy:
  logprob_batch_size: 2
  megatron_cfg:
    tensor_model_parallel_size: 8
    pipeline_model_parallel_size: 16
    expert_model_parallel_size: 16
  generation:
    colocated:
      enabled: false
      resources:
        num_nodes: 32
        gpus_per_node: 8
    vllm_cfg:
      tensor_parallel_size: 32
      gpu_memory_utilization: 0.8
      async_engine: true
logger:
  log_dir: logs/async-grpo-deepseek-v3-64n8g-32T32G
  wandb:
    name: async-grpo-deepseek-v3-64n8g-32T32G
cluster:
  gpus_per_node: 8
  num_nodes: 64
