defaults: ./grpo-qwen3-32b-4n4g-async-1off-megatron-dynamiccp-10step.yaml
policy:
  make_sequence_length_divisible_by: 16
  megatron_cfg:
    context_parallel_size: 4
    dynamic_context_parallel:
      enabled: false
logger:
  log_dir: logs/grpo-qwen3-32b-4n4g-async-staticcp-10step
  wandb:
    name: qwen3-32b-4n4g-async-staticcp-10step
