defaults: ../grpo-dapomath17k-nanov3-30BA3B-8n4g-megatron-trtllm.yaml
grpo:
  num_prompts_per_step: 8
  num_generations_per_prompt: 8
  max_num_steps: 5
  val_period: 1000
  val_at_start: false
  val_at_end: false
checkpointing:
  enabled: false
  checkpoint_dir: results/grpo-nemotron3-nano-30ba3b-8n4g-dynamiccp-quick
policy:
  train_global_batch_size: 64
  train_micro_batch_size: 1
  logprob_batch_size: 1
  max_total_sequence_length: 8192
  make_sequence_length_divisible_by: 4
  megatron_cfg:
    tensor_model_parallel_size: 2
    pipeline_model_parallel_size: 1
    num_layers_in_first_pipeline_stage: null
    num_layers_in_last_pipeline_stage: null
    context_parallel_size: 1
    expert_tensor_parallel_size: 1
    expert_model_parallel_size: 8
    sequence_parallel: true
    moe_hybridep_prepad_packed_inputs: false
    dynamic_context_parallel:
      enabled: true
      min_size: 1
      max_size: 16
      tokens_per_rank: 4096
    fp8_cfg:
      enabled: false
  sequence_packing:
    enabled: true
  dynamic_batching:
    enabled: false
  generation:
    max_new_tokens: 4096
logger:
  log_dir: logs/grpo-nemotron3-nano-30ba3b-8n4g-dynamiccp-quick
  wandb_enabled: true
  tensorboard_enabled: true
  wandb:
    project: nemo-rl
    name: grpo-nemotron3-nano-30ba3b-8n4g-dynamiccp-quick
data_plane:
  enabled: false
