defaults: ./grpo-qwen3-32b-4n4g-megatron-dynamiccp-quick.yaml
grpo:
  max_num_steps: 10
logger:
  log_dir: logs/grpo-qwen3-32b-4n4g-megatron-dynamiccp-profile
  wandb_enabled: true
  tensorboard_enabled: true
  wandb:
    project: nemo-rl-dynamic-cp
    name: qwen3-32b-4n4g-dynamic-cp-profile
