defaults: ../../../grpo_math_1B.yaml
grpo:
  num_prompts_per_step: 64
  num_generations_per_prompt: 32
loss_fn:
  use_importance_sampling_correction: true
checkpointing:
  enabled: false
  checkpoint_dir: results/grpo-qwen3-32b-4n8g-fp8
policy:
  model_name: Qwen/Qwen3-32B
  train_micro_batch_size: 1
  max_total_sequence_length: 4096
  dtensor_cfg:
    enabled: false
  optimizer: null
  scheduler: null
  make_sequence_length_divisible_by: ${policy.megatron_cfg.tensor_model_parallel_size}
  megatron_cfg:
    enabled: true
    empty_unused_memory_level: 1
    tensor_model_parallel_size: 4
    pipeline_model_parallel_size: 4
    sequence_parallel: true
    optimizer:
      lr: 3.0e-07
      min_lr: 3.0e-08
    scheduler:
      lr_warmup_iters: 2
      lr_warmup_init: 3.0e-08
    fp8_cfg:
      enabled: true
      fp8: e4m3
      fp8_recipe: blockwise
      fp8_param: false
    env_vars:
      NVTE_FP8_BLOCK_SCALING_FP32_SCALES: '1'
  generation:
    vllm_cfg:
      tensor_parallel_size: 4
      precision: fp8
      use_deep_gemm: true
logger:
  log_dir: logs/grpo-qwen3-32b-4n8g-fp8
  wandb_enabled: true
  tensorboard_enabled: true
  wandb:
    project: nemo-rl
    name: grpo-qwen3-32b-4n8g-fp8
cluster:
  gpus_per_node: 8
  num_nodes: 4
