defaults: ./grpo-qwen3-235b-32n4g-async-1off-mxfp8-rollout.yaml
checkpointing:
  checkpoint_dir: results/grpo-qwen3-235b-16n8g-async-1off-mxfp8-rollout  # pragma: allowlist secret
policy:
  generation:
    colocated:
      resources:
        num_nodes: 8
        gpus_per_node: 8
logger:
  log_dir: logs/grpo-qwen3-235b-16n8g-async-1off-mxfp8-rollout
  wandb:
    name: grpo-qwen3-235b-16n8g-async-1off-mxfp8-rollout
cluster:
  gpus_per_node: 8
  num_nodes: 16
  segment_size: 8
