defaults: ./grpo-qwen3-30ba3b-4n8g-async-1off.yaml
checkpointing:
  checkpoint_dir: results/grpo-qwen3-30ba3b-4n8g-async-1off-mxfp8-rollout
policy:
  generation:
    vllm_cfg:
      precision: "fp8"
      is_mx: true
      refit_prequantize: true
      refit_cache_loader_routes: true
      quantization_ignored_layer_kws:
        - q_proj
        - k_proj
        - v_proj
        - o_proj
        - ".mlp.gate"
    vllm_kwargs:
      moe_backend: flashinfer_trtllm
logger:
  log_dir: logs/grpo-qwen3-30ba3b-4n8g-async-1off-mxfp8-rollout
  wandb:
    name: grpo-qwen3-30ba3b-4n8g-async-1off-mxfp8-rollout
