defaults: ./grpo-qwen3-32b-4n4g-megatron-dynamiccp-quick.yaml
grpo:
  max_num_steps: 10
logger:
  log_dir: logs/grpo-qwen3-32b-4n4g-megatron-dynamiccp-10step
  wandb_enabled: true
  tensorboard_enabled: true
  wandb:
    project: nemo-rl-cp-comparison
    name: qwen3-32b-4n4g-dynamic-cp-10step
