# Copyright (c) 2023, NVIDIA CORPORATION.  All rights reserved.

[build-system]
requires = [
    "setuptools",
    "pybind11",
    "torch",
    "nvidia-mathdx==25.1.1",
]
build-backend = "setuptools.build_meta"

[project]
name = "kitchen"
dynamic = ["dependencies", "version"]
