# syntax=docker/dockerfile:1
# Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
FROM nvcr.io/nvidia/cuda-dl-base@sha256:8c9b9b6d878238915e3c379bb75ef56087b45f5c2c910fcf5331749e0008c2c4
USER root
WORKDIR /opt/nemo-rl
COPY . /opt/nemo-rl
RUN bash docker/nano35/build_core.sh
ENV NRL_CONTAINER=1 \
    UV_PYTHON_INSTALL_DIR=/opt/uv/python \
    UV_PROJECT_ENVIRONMENT=/opt/nemo_rl_venv \
    NEMO_RL_VENV_DIR=/opt/ray_venvs \
    NEMO_GYM_VENV_DIR=/opt/gym_venvs \
    PATH=/opt/nemo_rl_venv/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin
ENTRYPOINT ["bash", "/opt/nemo-rl/docker/nano35/entrypoint.sh"]
CMD ["bash"]
