# GRPO Algorithm Configuration
# inherit from grpo-qwen2.5-vl-3b-instruct-clevr-1n2g-dtensor2tp1.v1.yaml
defaults:
  - grpo-qwen2.5-vl-3b-instruct-clevr-1n2g-dtensor2tp1.v1.yaml

checkpointing:
  enabled: true
  checkpoint_dir: "results/refcoco_grpo_${policy.model_name}"
  metric_name: "val_reward"
  higher_is_better: true
  keep_top_k: 3
  save_period: 10

policy:
  generation:
    backend: "vllm"
    max_new_tokens: 1024
  
  scheduler:
    - name: "torch.optim.lr_scheduler.LinearLR"
      kwargs:
        start_factor: 0.1
        end_factor: 1.0
        total_iters: 20
    - name: "torch.optim.lr_scheduler.ConstantLR"
      kwargs:
        factor: 1.0
        total_iters: 10000000000
    - milestones: [20]

data:
  prompt_file: "examples/prompts/refcoco.txt"
  system_prompt_file: null
  download_dir: "/data/coco/"
  dataset_name: "refcoco"
  split: "default"

cluster:
  gpus_per_node: 8
