defaults: sft-super67b-generalist.n64dss.yaml
policy:
  train_global_batch_size: 32
cluster:
  gpus_per_node: 4
  num_nodes: 64
data:
  energon:
    nvdataset_cache_dir: /home/svc-dss/cache/nemotron
    watchdog_timeout_seconds: 1200
    num_workers: 1
    prefetch_factor: 2
    cache_pool_num_workers: 4
    cache_pool_max_gbytes: 128
    gc_collect_every_n_steps: 100000
    model_family: nemotron
    task_encoder:
      options:
        allow_large_videos: true
        video_max_num_frames: 64
        video_aug_scale_frames_up: 4
        video_aug_scale_resolution_only: true
        video_decode_thread_count: 4
      packing:
        name: balanced_greedy_knapsack
        buffer_size: 5000
        options:
          max_sequence_length: ${policy.max_total_sequence_length}
          sequence_length_pad_multiple: 64
          balanced_knapsack_delta: 5
    cookers:
    - name: nemotron_conversation
      has_subflavors:
        cook: conversation
    - name: nemotron_general_conversations_jsonl
      has_subflavors:
        cook: general_conversations_jsonl
    - name: nemotron_general_conversations_webdataset
      has_subflavors:
        cook: general_conversations_webdataset
    - name: nemotron_nano_openai_messages_jsonl
      has_subflavors:
        cook: openai_messages_jsonl
    seed_offset: 0
  train:
    path: /opt/nemo-rl/examples/configs/sft_v2_tests/sft_super35_generalist_full_cmh.yaml
    split: train
    virtual_epoch_length: 10000000
  validation: null
logger:
  monitor_gpus: false
  log_dir: logs/sft-super67b-n64-dss-generalist-v2
  wandb:
    name: sft-super67b-n64-dss-generalist-v2
  tensorboard:
    log_dir: logs/sft-super67b-n64-dss-generalist-v2
checkpointing:
  checkpoint_dir: /data/nemorl-runs/sft-super67b-n64-dss-generalist-v2
