defaults: sft-super67b-generalist.n64dss_v2.yaml
policy:
  train_global_batch_size: 32
cluster:
  num_nodes: 128
logger:
  log_dir: logs/sft-super67b-n128-dss-generalist-v2
  wandb:
    name: sft-super67b-n128-dss-generalist-v2
  tensorboard:
    log_dir: logs/sft-super67b-n128-dss-generalist-v2
checkpointing:
  checkpoint_dir: /data/nemorl-runs/sft-super67b-n128-dss-generalist-v2
