#!/usr/bin/env bash
set -Eeuo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)"

# Reproduce the legacy chunk=1 / 1x8 experiment that reached Step 25. Its
# deleted checkpoint cannot be resumed, so this run starts independently from
# the same RFC0037 SFT step-400 weights for a controlled recipe comparison.
export MOLT_RUN_NAME=osworld361-molt-legacy-chunk1-repro
export NANO_OMNI_MODEL_NAME=/lustre/fsw/portfolios/llmservice/projects/llmservice_nemo_reasoning/users/jianh/projects/OpenRLHF-main/ckpts/rfc0037-sft-step400

export MOLT_MAX_STEPS=200
export OSWORLD_NUM_PROMPTS_PER_STEP=1
export OSWORLD_NUM_GENERATIONS=8
export MOLT_VLLM_GENERATE_BATCH_SIZE=16
export MOLT_ASYNC_QUEUE_SIZE=2
export MOLT_MAX_STALENESS=8
export GRPO_MAX_NUM_EPOCHS=100000

export NUM_NODES=4
export MOLT_INFERENCE_NODES=3
export MOLT_TENSOR_PARALLEL_SIZE=1
export MOLT_EXPERT_MODEL_PARALLEL_SIZE=8
export MOLT_CONTEXT_PARALLEL_SIZE=8
export MOLT_PIPELINE_PARALLEL_SIZE=1
export MOLT_SEQUENCE_LENGTH_DIVISOR=32

export OSWORLD_LEARNING_RATE=5e-6
export MOLT_ADAM_BETA1=0.9
export MOLT_ADAM_BETA2=0.999
export MOLT_ROUTER_REPLAY_ENABLED=true
export MOLT_IS_RATIO_MIN=0.99
export MOLT_IS_RATIO_MAX=1.01

export OSWORLD_TEMPERATURE=1.0
export OSWORLD_TOP_P=1.0
export OSWORLD_MAX_MODEL_LEN=49152
export OSWORLD_MAX_NEW_TOKENS=16384
export OSWORLD_AGENT_MAX_TOKENS=16384
export OSWORLD_MAX_STEPS=150
export OSWORLD_MAX_IMAGE_HISTORY_LENGTH=3
export OSWORLD_MAX_ACTIVE_IMAGES=10
export OSWORLD_VLLM_MAX_IMAGES=20
export OSWORLD_CC_KEEP_LAST_IMAGE_GROUPS=2
export OSWORLD_CC_ACTIONS_PER_CHUNK=100
export OSWORLD_CC_MAX_TOTAL_TOKENS=49152
export OSWORLD_CC_RESERVED_GENERATION_TOKENS=11152
export OSWORLD_SLEEP_AFTER_EXECUTION=3
export OSWORLD_NEMO_GYM_NUM_WORKERS=128
export OSWORLD_MAX_PARALLEL_ROLLOUTS=128

# Preserve the resolved vLLM settings recorded by legacy job 16644143.
export OSWORLD_VLLM_GPU_MEMORY_UTILIZATION=0.5
export OSWORLD_VLLM_ENABLE_PREFIX_CACHING=false
export OSWORLD_VLLM_ENABLE_CHUNKED_PREFILL=false
export OSWORLD_VLLM_MAX_NUM_BATCHED_TOKENS=49152
export OSWORLD_VLLM_EXPERT_PARALLEL_SIZE=1

export NEMOTRON_OMNI_VISION_CHUNK_SIZE=1
export NEMOTRON_OMNI_VISION_CACHE_MAX_ENTRIES=128
export MOLT_OPTIMIZER_CPU_OFFLOAD=true
export MOLT_OPTIMIZER_OFFLOAD_FRACTION=1.0
export MOLT_OFFLOAD_OPTIMIZER_FOR_LOGPROB=true

export CHECKPOINTING_ENABLED=true
export CHECKPOINT_SAVE_PERIOD=5
export CHECKPOINT_KEEP_TOP_K=1
export MOLT_SAVE_OPTIMIZER=false
export OSWORLD_VAL_PERIOD=100000
export OSWORLD_VAL_AT_START=false
export OSWORLD_VAL_AT_END=false

export SBATCH_PARTITION="${SBATCH_PARTITION:-batch}"
export SBATCH_TIME="${SBATCH_TIME:-04:00:00}"
export OSWORLD_CHECKPOINT_MUST_SAVE_BY=00:03:40:00

exec "${ROOT}/examples/nemo_gym/submit_osworld_molt_jianh_parity.sh"
