#!/usr/bin/env bash
set -Eeuo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)"

# Validated Molt batch-parity experiment: B=8 prompt groups per optimizer
# step, N=8 rollouts per prompt, and K=8 groups concurrently in flight.
export MOLT_RUN_NAME="${MOLT_RUN_NAME:-osworld361-molt-aligned-v1-b8k8}"
export MOLT_ALIGNMENT_PROFILE=b8k8
: "${NANO_OMNI_MODEL_NAME:?Set NANO_OMNI_MODEL_NAME to the SFT checkpoint}"
export MOLT_REFERENCE_MODEL="${MOLT_REFERENCE_MODEL:-${NANO_OMNI_MODEL_NAME}}"

export MOLT_MAX_STEPS="${MOLT_MAX_STEPS:-300}"
export OSWORLD_NUM_PROMPTS_PER_STEP=8
export OSWORLD_NUM_GENERATIONS=8
export MOLT_VLLM_GENERATE_BATCH_SIZE=8
export MOLT_ASYNC_QUEUE_SIZE=2
export MOLT_MAX_STALENESS=1
export MOLT_DRAIN_INFLIGHT_BEFORE_REFIT=false
export MOLT_REFIT_RPC_TIMEOUT_S=600
export MOLT_CONTROL_RPC_TIMEOUT_S=120
export MOLT_CHECKPOINT_FINALIZE_TIMEOUT_S=600
export OSWORLD_ROLLOUT_TIMEOUT_S=1200
export MOLT_ROLLOUT_BATCH_TIMEOUT_S=3600
export GRPO_MAX_NUM_EPOCHS=100000

export NUM_NODES=4
export MOLT_INFERENCE_NODES=3
export MOLT_TENSOR_PARALLEL_SIZE=1
export MOLT_EXPERT_MODEL_PARALLEL_SIZE=8
export MOLT_CONTEXT_PARALLEL_SIZE=8
export MOLT_PIPELINE_PARALLEL_SIZE=1
export MOLT_SEQUENCE_LENGTH_DIVISOR=32

export OSWORLD_LEARNING_RATE=5e-6
export MOLT_ADAM_BETA1=0.9
export MOLT_ADAM_BETA2=0.99
export MOLT_LR_WARMUP_ITERS=9
export MOLT_LR_WARMUP_INIT=0.0
export MOLT_ROUTER_REPLAY_ENABLED=true
export MOLT_IS_RATIO_MIN=0.99
export MOLT_IS_RATIO_MAX=1.01

export OSWORLD_TEMPERATURE=1.0
export OSWORLD_TOP_P=1.0
export OSWORLD_MAX_MODEL_LEN=49152
export OSWORLD_MAX_NEW_TOKENS=16384
export OSWORLD_AGENT_MAX_TOKENS=16384
export OSWORLD_MAX_STEPS=150
export OSWORLD_ACTION_TIMEOUT_S=60
export OSWORLD_LLM_TIMEOUT_S=900
export OSWORLD_MAX_IMAGE_HISTORY_LENGTH=3
export OSWORLD_MAX_ACTIVE_IMAGES=10
export OSWORLD_VLLM_MAX_IMAGES=20
export OSWORLD_CC_KEEP_LAST_IMAGE_GROUPS=2
export OSWORLD_CC_ACTIONS_PER_CHUNK=100
export OSWORLD_CC_MAX_TOTAL_TOKENS=49152
export OSWORLD_CC_RESERVED_GENERATION_TOKENS=11152
export OSWORLD_SLEEP_AFTER_EXECUTION=5
# Admit K=8 prompt groups while capping active desktop work at 32 rollouts.
export OSWORLD_NEMO_GYM_NUM_WORKERS=32
export OSWORLD_MAX_PARALLEL_ROLLOUTS=32

export OSWORLD_VLLM_GPU_MEMORY_UTILIZATION=0.8
export OSWORLD_VLLM_ENABLE_PREFIX_CACHING=true
export OSWORLD_VLLM_ENABLE_CHUNKED_PREFILL=true
export OSWORLD_VLLM_MAX_NUM_BATCHED_TOKENS=4096
export OSWORLD_VLLM_EXPERT_PARALLEL_SIZE=2
export OSWORLD_VLLM_ATTENTION_BACKEND=TRITON_ATTN
export OSWORLD_VLLM_MM_ENCODER_ATTN_BACKEND=TORCH_SDPA
export OSWORLD_VLLM_GDN_PREFILL_BACKEND=triton

export MOLT_SEQUENCE_PACKING_ENABLED=true
export MOLT_TRAIN_MB_TOKENS=49152
export MOLT_LOGPROB_MB_TOKENS=49152
export NEMOTRON_OMNI_VISION_CHUNK_SIZE=1
export NEMOTRON_OMNI_VISION_CACHE_MAX_ENTRIES=0
export RAY_ENABLE_ZERO_COPY_TORCH_TENSORS=1
export MOLT_OPTIMIZER_CPU_OFFLOAD=true
export MOLT_OPTIMIZER_OFFLOAD_FRACTION=1.0
export MOLT_OFFLOAD_OPTIMIZER_FOR_LOGPROB=true

export CHECKPOINTING_ENABLED="${CHECKPOINTING_ENABLED:-true}"
export CHECKPOINT_SAVE_PERIOD=1
export CHECKPOINT_KEEP_TOP_K=2
export MOLT_SAVE_OPTIMIZER=true
export OSWORLD_VAL_PERIOD=100000
export OSWORLD_VAL_AT_START=false
export OSWORLD_VAL_AT_END=false
export WANDB_ENABLED="${WANDB_ENABLED:-true}"
export WANDB_PROJECT="${WANDB_PROJECT:-osworld-context-compaction}"
export WANDB_GROUP="${WANDB_GROUP:-osworld-molt-aligned-v1}"
export WANDB_RUN_NAME="${WANDB_RUN_NAME:-${MOLT_RUN_NAME}}"

export SBATCH_PARTITION="${SBATCH_PARTITION:-batch}"
export SBATCH_TIME="${SBATCH_TIME:-04:00:00}"
export OSWORLD_CHECKPOINT_MUST_SAVE_BY="${OSWORLD_CHECKPOINT_MUST_SAVE_BY:-00:03:40:00}"
export MOLT_AUTO_RESUME_CHAIN="${MOLT_AUTO_RESUME_CHAIN:-true}"
export MOLT_CHAIN_DEPTH="${MOLT_CHAIN_DEPTH:-0}"
export MOLT_CHAIN_MAX="${MOLT_CHAIN_MAX:-80}"

exec "${ROOT}/examples/nemo_gym/submit_osworld_molt_jianh_parity.sh"
