checkpointing:
  checkpoint_dir: /home/phuc/workspace/rl/small_prs/pr001_tinker_mvp/RL_multilora_native/results/code7x_native_noclip_multi
  checkpoint_must_save_by: null
  enabled: true
  higher_is_better: false
  keep_top_k: 100
  metric_name: null
  save_period: 250
cluster:
  gpus_per_node: 8
  num_nodes: 1
data:
  add_bos: true
  add_eos: true
  add_generation_prompt: false
  default:
    processor: sft_processor
    prompt_file: null
    system_prompt_file: null
  max_input_seq_length: 512
  num_workers: 1
  shuffle: false
  train:
    dataset_name: openai_format
    split: train
    data_path: /home/phuc/multi_lora_data/hellaswag_train_a.jsonl
    chat_key: messages
    use_preserving_dataset: false
  validation:
    dataset_name: openai_format
    split: validation
    data_path: /home/phuc/multi_lora_data/hellaswag_val.jsonl
    chat_key: messages
    use_preserving_dataset: false
logger:
  gpu_monitoring:
    collection_interval: 10
    flush_interval: 10
  log_dir: /home/phuc/workspace/rl/small_prs/pr001_tinker_mvp/RL_multilora_native/results/code7x_native_noclip_multi_logs
  mlflow:
    experiment_name: sft-dev
    run_name: sft-dev-${data.train.dataset_name}
  mlflow_enabled: false
  monitor_gpus: false
  swanlab:
    name: sft-dev-${data.train.dataset_name}
    project: sft-dev
  swanlab_enabled: false
  tensorboard:
    log_dir: tb_logs-sft-dev-${data.train.dataset_name}
  tensorboard_enabled: false
  wandb:
    name: code7x_pre10_multi
    project: nous-multi-lora-equivalence
  wandb_enabled: false
policy:
  dtensor_cfg:
    _v2: true
    activation_checkpointing: true
    context_parallel_size: 1
    cpu_offload: false
    custom_parallel_plan: null
    enabled: true
    env_vars: {}
    lora_cfg:
      alpha: 128
      dim: 64
      dropout: 0.0
      dropout_position: post
      enabled: true
      exclude_modules: []
      lora_A_init: xavier
      match_all_linear: false
      target_modules:
      - '*q_proj'
      - '*k_proj'
      - '*v_proj'
      - '*o_proj'
      - '*in_proj'
      - '*out_proj'
      - '*up_proj'
      - '*down_proj'
      use_triton: false
    sequence_parallel: false
    tensor_parallel_size: 1
    expert_parallel_size: 1
    automodel_kwargs:
      force_hf: false
  dynamic_batching:
    enabled: false
    sequence_length_round: 64
    train_mb_tokens: ${mul:${policy.max_total_sequence_length}, ${policy.train_micro_batch_size}}
  make_sequence_length_divisible_by: 208
  max_grad_norm: null
  max_total_sequence_length: 512
  megatron_cfg:
    activation_checkpointing: false
    apply_rope_fusion: true
    bias_activation_fusion: true
    context_parallel_size: 1
    defer_fp32_logits: false
    distributed_data_parallel_config:
      data_parallel_sharding_strategy: optim_grads_params
      grad_reduce_in_fp32: false
      overlap_grad_reduce: true
      overlap_param_gather: true
      use_custom_fsdp: false
    empty_unused_memory_level: 1
    enabled: false
    env_vars: {}
    expert_model_parallel_size: 1
    expert_tensor_parallel_size: 1
    fp8_cfg:
      enabled: false
      fp8: e4m3
      fp8_param: false
      fp8_recipe: blockwise
    freeze_moe_router: false
    moe_enable_deepep: false
    moe_per_layer_logging: false
    moe_permute_fusion: false
    moe_router_bias_update_rate: 1e-3
    moe_router_dtype: null
    moe_router_load_balancing_type: aux_loss
    moe_shared_expert_overlap: false
    moe_token_dispatcher_type: allgather
    num_layers_in_first_pipeline_stage: null
    num_layers_in_last_pipeline_stage: null
    optimizer:
      adam_beta1: 0.9
      adam_beta2: 0.98
      adam_eps: 1e-5
      bf16: true
      clip_grad: ${policy.max_grad_norm}
      fp16: false
      lr: 5.0e-06
      min_lr: 4.9999e-06
      optimizer: adam
      optimizer_cpu_offload: false
      optimizer_offload_fraction: 0.0
      params_dtype: float32
      sgd_momentum: 0.9
      use_distributed_optimizer: true
      use_precision_aware_optimizer: true
      weight_decay: 0.1
    peft:
      a2a_experimental: false
      alpha: 32
      dim: 8
      dropout: 0.0
      dropout_position: post
      enabled: false
      exclude_modules: []
      lora_A_init_method: xavier
      lora_B_init_method: zero
      lora_dtype: None
      target_modules: []
    pipeline_dtype: ${policy.precision}
    pipeline_model_parallel_size: 1
    scheduler:
      end_weight_decay: ${policy.megatron_cfg.optimizer.weight_decay}
      lr_decay_iters: 1000
      lr_decay_style: constant
      lr_warmup_init: 4.9999e-06
      lr_warmup_iters: 50
      start_weight_decay: ${policy.megatron_cfg.optimizer.weight_decay}
      weight_decay_incr_style: constant
    sequence_parallel: false
    tensor_model_parallel_size: 1
  model_name: nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16
  offload_optimizer_for_logprob: false
  optimizer:
    kwargs:
      betas:
      - 0.9
      - 0.98
      eps: 1.0e-05
      foreach: false
      fused: true
      lr: 0.0005
      weight_decay: 0.01
    name: torch.optim.AdamW
  precision: bfloat16
  sequence_packing:
    algorithm: modified_first_fit_decreasing
    enabled: false
    sequence_length_round: 64
    train_mb_tokens: ${mul:${policy.max_total_sequence_length}, ${policy.train_micro_batch_size}}
  tokenizer:
    chat_template: '{% for message in messages %}{%- if message[''role''] == ''system''  %}{{''Context:
      '' + message[''content''].strip()}}{%- elif message[''role''] == ''user''  %}{{''
      Question: '' + message[''content''].strip() + '' Answer:''}}{%- elif message[''role'']
      == ''assistant''  %}{{'' '' + message[''content''].strip()}}{%- endif %}{% endfor
      %}'
    chat_template_kwargs: null
    name: nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16
  train_global_batch_size: 64
  train_micro_batch_size: 8
  seq_length: 512
  scheduler:
  - name: torch.optim.lr_scheduler.LinearLR
    kwargs:
      start_factor: 0.01
      total_iters: 10
  - milestones:
    - 10
  - name: torch.optim.lr_scheduler.CosineAnnealingLR
    kwargs:
      T_max: 1490
      eta_min: 5.0e-05
sft:
  max_num_epochs: 100
  max_num_steps: 10
  seed: 42
  val_at_end: false
  val_at_start: false
  val_batches: 8
  val_global_batch_size: 4
  val_micro_batch_size: 1
  val_period: 0
  save_freq: 250
multi_lora:
  enabled: true
  schedule: round_robin
  global_batch_size: 64
  batch_size_per_adapter: 16
  storage_device: cuda
  execution_mode: concurrent
  adapters:
  - name: adapter_a
    pin: auto
    lora_cfg:
      enabled: true
      dim: 64
      alpha: 128
      match_all_linear: false
      target_modules:
      - '*q_proj'
      - '*k_proj'
      - '*v_proj'
      - '*o_proj'
      - '*in_proj'
      - '*out_proj'
      - '*up_proj'
      - '*down_proj'
      dropout: 0.0
    optimizer:
      name: torch.optim.AdamW
      kwargs:
        lr: 0.0005
        weight_decay: 0.01
        betas:
        - 0.9
        - 0.98
        eps: 1.0e-05
        foreach: false
        fused: true
    data:
      train:
        dataset_name: openai_format
        data_path: /home/phuc/multi_lora_data/hellaswag_train_a.jsonl
        chat_key: messages
        use_preserving_dataset: false
      validation:
        dataset_name: openai_format
        data_path: /home/phuc/multi_lora_data/hellaswag_val.jsonl
        chat_key: messages
        use_preserving_dataset: false
  - name: adapter_b
    pin: auto
    lora_cfg:
      enabled: true
      dim: 64
      alpha: 128
      match_all_linear: false
      target_modules:
      - '*q_proj'
      - '*k_proj'
      - '*v_proj'
      - '*o_proj'
      - '*in_proj'
      - '*out_proj'
      - '*up_proj'
      - '*down_proj'
      dropout: 0.0
    optimizer:
      name: torch.optim.AdamW
      kwargs:
        lr: 0.0005
        weight_decay: 0.01
        betas:
        - 0.9
        - 0.98
        eps: 1.0e-05
        foreach: false
        fused: true
    data:
      train:
        dataset_name: openai_format
        data_path: /home/phuc/multi_lora_data/hellaswag_train_b.jsonl
        chat_key: messages
        use_preserving_dataset: false
      validation:
        dataset_name: openai_format
        data_path: /home/phuc/multi_lora_data/hellaswag_val.jsonl
        chat_key: messages
        use_preserving_dataset: false
  - name: adapter_c
    pin: auto
    lora_cfg:
      enabled: true
      dim: 64
      alpha: 128
      match_all_linear: false
      target_modules:
      - '*q_proj'
      - '*k_proj'
      - '*v_proj'
      - '*o_proj'
      - '*in_proj'
      - '*out_proj'
      - '*up_proj'
      - '*down_proj'
      dropout: 0.0
    optimizer:
      name: torch.optim.AdamW
      kwargs:
        lr: 0.0005
        weight_decay: 0.01
        betas:
        - 0.9
        - 0.98
        eps: 1.0e-05
        foreach: false
        fused: true
    data:
      train:
        dataset_name: openai_format
        data_path: /home/phuc/multi_lora_data/hellaswag_train_c.jsonl
        chat_key: messages
        use_preserving_dataset: false
      validation:
        dataset_name: openai_format
        data_path: /home/phuc/multi_lora_data/hellaswag_val.jsonl
        chat_key: messages
        use_preserving_dataset: false
  - name: adapter_d
    pin: auto
    lora_cfg:
      enabled: true
      dim: 64
      alpha: 128
      match_all_linear: false
      target_modules:
      - '*q_proj'
      - '*k_proj'
      - '*v_proj'
      - '*o_proj'
      - '*in_proj'
      - '*out_proj'
      - '*up_proj'
      - '*down_proj'
      dropout: 0.0
    optimizer:
      name: torch.optim.AdamW
      kwargs:
        lr: 0.0005
        weight_decay: 0.01
        betas:
        - 0.9
        - 0.98
        eps: 1.0e-05
        foreach: false
        fused: true
    data:
      train:
        dataset_name: openai_format
        data_path: /home/phuc/multi_lora_data/hellaswag_train_d.jsonl
        chat_key: messages
        use_preserving_dataset: false
      validation:
        dataset_name: openai_format
        data_path: /home/phuc/multi_lora_data/hellaswag_val.jsonl
        chat_key: messages
        use_preserving_dataset: false
