# GRPO Algorithm Configuration
defaults: "grpo_math_1B.yaml"

policy:
  model_name: "meta-llama/Llama-3.1-8B-Instruct"
  train_global_batch_size: 32
  train_micro_batch_size: 1
  generation_batch_size: 32
  learning_rate: 5.0e-6
  logprob_batch_size: 2
  max_total_sequence_length: 4096

  scheduler:
    - name: "torch.optim.lr_scheduler.LinearLR"
      kwargs:
        start_factor: 0.1
        end_factor: 1.0
        total_iters: 50
    - name: "torch.optim.lr_scheduler.ConstantLR"
      kwargs:
        factor: 1.0
        total_iters: 10000000000
    - milestones: [50]

  generation:
    backend: "vllm"
    max_new_tokens: ${policy.max_total_sequence_length}
    temperature: 1.0
    top_p: 1.0
    top_k: null
    vllm_cfg:
      tensor_parallel_size: 1
      gpu_memory_utilization: 0.6
      max_model_len: ${policy.max_total_sequence_length}
    
cluster:
  gpus_per_node: 8
  num_nodes: 1