# GRPO configuration for unique numbers environment
defaults: "grpo_math_8B.yaml"

grpo:
  num_prompts_per_step: 32
  num_generations_per_prompt: 16
  max_rollout_turns: 20
  max_num_steps: 100
  val_at_start: true

data:
  add_system_prompt: false

checkpointing:
  enabled: false
  checkpoint_dir: "results/grpo-unique-numbers"
  metric_name: "val_reward"
  higher_is_better: true
  keep_top_k: 3
  save_period: 10

env:
  unique_numbers:
    cfg:
      max_turns: 15
      min_length: 5
      max_length: 10
      max_integer: 15

logger:
  wandb_enabled: True 
  wandb:
    project: "grpo-simulated-retrieval"
    name: "llama-8b-__NOW__"


cluster:
  gpus_per_node: 8