# GRPO Algorithm Configuration
grpo:
  num_prompts_per_step: 1
  num_generations_per_prompt: 2
  max_num_steps: 1000000
  normalize_rewards: true
  use_leave_one_out_baseline: true
  val_period: 1000
  val_at_start: false
  max_val_samples: 256
  val_batch_size: 256

loss_fn:
  reference_policy_kl_penalty: 0.
  ratio_eps_min: 0.2
  ratio_eps_max: 0.2

checkpointing:
  enabled: false
  checkpoint_dir: "results/grpo"
  metric_name: "val_reward"
  higher_is_better: true
  keep_top_k: 3
  save_period: 10

policy:
  model_name: "Qwen/Qwen2-1.5B"
  train_global_batch_size: 2 
  train_micro_batch_size: 1
  generation_batch_size: 1
  logprob_batch_size: 1
  max_total_sequence_length: 2048
  precision: "bfloat16"
  offload_policy: False
  cpu_offload: False
  tensor_parallel_size: 2

  optimizer:
    name: "torch.optim.SGD"
    kwargs:
      lr: 1e-4
      # weight_decay: 0.01
      # betas: [0.9, 0.999]
      # eps: 1e-8

  scheduler:
    - name: "torch.optim.lr_scheduler.LinearLR"
      kwargs:
        start_factor: 0.1
        end_factor: 1.0
        total_iters: 50
    - name: "torch.optim.lr_scheduler.ConstantLR"
      kwargs:
        factor: 1.0
        total_iters: 10000000000
    - milestones: [50]

  generation:
    backend: "vllm"
    max_new_tokens: ${policy.max_total_sequence_length}
    temperature: 1.0
    top_p: 1.0
    top_k: null
    vllm_cfg:
      tensor_parallel_size: 2
      gpu_memory_utilization: 0.2
      max_model_len: ${policy.max_total_sequence_length}

data:
  max_input_seq_length: ${policy.max_total_sequence_length} # upper bound, real truncation occurs at vllm.max_model_len
  prompt_file: "examples/prompts/cot.txt"
  system_prompt_file: null
  dataset_name: "OpenMathInstruct-2"
  
env:
  math:
    num_workers: 1

logger:
  log_dir: "log_dummy"  # Base directory for all logs
  num_val_samples_to_print: 0 # Number of validation samples to pretty print on terminal
  wandb_enabled: false
  tensorboard_enabled: false
  monitor_gpus: false  # If true, will monitor GPU usage and log to wandb and/or tensorboard
  wandb:
    project: "grpo-dev"
    name: "grpo-dev-logger-dtensor"
  tensorboard: {}
  gpu_monitoring:
    collection_interval: 10  # How often to collect GPU usage metrics (in seconds)
    flush_interval: 10  # How often to flush GPU usage metrics to the loggers (in seconds)

cluster:
  gpus_per_node: 2
  num_nodes: 1
