# GRPO Algorithm Configuration
defaults: "grpo_math_qwen30ba3b_megatron.yaml"

loss_fn:
  reference_policy_kl_penalty: 0.01
  ratio_clip_min: 0.2
  ratio_clip_max: 0.2
  ratio_clip_c: null
  # (default off) loss formulation improvements (docs/guides/grpo.md#loss)
  use_on_policy_kl_approximation: false
  use_importance_sampling_correction: false
  sequence_level_importance_sampling: true
  # FIXME(pjin): should require token_level_loss = False.
  token_level_loss: true
