# GRPO Algorithm Configuration
defaults: "grpo-deepscaler-1.5b-8K.yaml"

loss_fn:
  use_importance_sampling_correction: True
  sequence_level_importance_ratios: True
  token_level_loss: False

policy:
  activation_checkpointing_enabled: True

  dtensor_cfg:
    tensor_parallel_size: 2
    activation_checkpointing: True

  generation:
    vllm_cfg:
      tensor_parallel_size: 2
