# SFT Algorithm Configuration
sft:
  num_steps: 1168251
  seed: 42

policy:
  model_name: "meta-llama/Meta-Llama-3-8B"
  train_global_batch_size: 128
  train_micro_batch_size: 1
  optimizer:
    name: "torch.optim.AdamW"
    kwargs:
      lr: 5.0e-6
      weight_decay: 0.1
      betas: [0.9, 0.98]
      eps: 1e-5

  scheduler:
    name: "torch.optim.lr_scheduler.LinearLR"
    kwargs:
      start_factor: 0.0196078
      end_factor: 1.0
      total_iters: 50
    
data:
  max_input_seq_length: 2048
  dataset_name: "squad"

logger:
  wandb_enabled: true
  tensorboard_enabled: false
  wandb:
    project: "sft-dev"
    name: "sft-dev-logger"
  tensorboard:
    log_dir: "tb_logs"

cluster:
  gpus_per_node: 8
  num_nodes: 1
