defaults: sft.yaml
sft:
  max_num_steps: 1000000
  val_period: 500
  val_batches: 4
  val_global_batch_size: 128
  val_micro_batch_size: 2
checkpointing:
  checkpoint_dir: results/sft_openmathinstruct2
  keep_top_k: 100
  save_period: 500
policy:
  model_name: meta-llama/Llama-3.1-8B
  tokenizer:
    name: meta-llama/Llama-3.1-8B-Instruct
  train_global_batch_size: 512
  train_micro_batch_size: 2
  max_total_sequence_length: 4096
  dtensor_cfg:
    tensor_parallel_size: 4
<<<<<<< sfawzy_megatron_recipes
    context_parallel_size: 1
    custom_parallel_plan: null

  megatron_recipe: megatron.bridge.recipes.llama.llama31_8b_pretrain_config
  megatron_cfg:
    enabled: false

  dynamic_batching:
    enabled: false

  sequence_packing:
    enabled: false
    train_mb_tokens: ${mul:${policy.max_total_sequence_length}, ${policy.train_micro_batch_size}}
    algorithm: "modified_first_fit_decreasing"
    sequence_length_round: 64

  # makes the training sequence length divisible by the tensor parallel size
  # this is useful for sequence parallel training
  make_sequence_length_divisible_by: ${policy.dtensor_cfg.tensor_parallel_size}
=======
>>>>>>> main
  max_grad_norm: null
  optimizer:
    kwargs:
      lr: 2.0e-05
      weight_decay: 0.01
      eps: 1.0e-08
data:
  add_generation_prompt: true
  train:
    dataset_name: OpenMathInstruct-2
    output_key: generated_solution
    split: train_1M
    split_validation_size: 0.05
    seed: ${sft.seed}
  validation: null
  default:
    prompt_file: examples/prompts/math.txt
logger:
  monitor_gpus: false
  wandb:
    name: openmathinstruct-nemorl-1M_train
  swanlab:
    name: openmathinstruct-nemorl-1M_train
  tensorboard:
    log_dir: tb_logs-openmathinstruct-nemorl-1M_train
  mlflow:
    run_name: openmathinstruct-nemorl-1M_train
cluster:
  gpus_per_node: 8
