#!/usr/bin/env python3
"""Generate Slurm submit scripts for EAGLE TAR-drift GRPO A/B runs.

This generates one Slurm script per seed. Each generated script runs two arms
sequentially under the same allocation:
1) train arm (reasonable GRPO updates)
2) frozen arm (same config, LR=0.0)

It also generates a submit_all.sh helper that submits all per-seed scripts.
"""

from __future__ import annotations

import argparse
from datetime import datetime
from pathlib import Path
from typing import Iterable


def _csv_ints(raw: str) -> list[int]:
    values: list[int] = []
    for item in raw.split(","):
        item = item.strip()
        if not item:
            continue
        values.append(int(item))
    if not values:
        raise ValueError("No seeds parsed from --seeds")
    return values


def _slurm_header(seed: int, args: argparse.Namespace) -> str:
    out = [
        "#!/usr/bin/env bash",
        "# Auto-generated by tools/generate_eagle_tar_drift_slurm_submits.py",
        f"#SBATCH --job-name={args.job_prefix}-s{seed}",
        f"#SBATCH --nodes={args.nodes}",
        "#SBATCH --ntasks=1",
        f"#SBATCH --cpus-per-task={args.cpus_per_task}",
        f"#SBATCH --time={args.time_limit}",
        f"#SBATCH --output={args.slurm_log_dir}/slurm-%x-%j.out",
        f"#SBATCH --error={args.slurm_log_dir}/slurm-%x-%j.err",
    ]

    if args.partition:
        out.append(f"#SBATCH --partition={args.partition}")
    if args.account:
        out.append(f"#SBATCH --account={args.account}")
    if args.qos:
        out.append(f"#SBATCH --qos={args.qos}")
    if args.constraint:
        out.append(f"#SBATCH --constraint={args.constraint}")
    if args.gres:
        out.append(f"#SBATCH --gres={args.gres}")
    if args.mem:
        out.append(f"#SBATCH --mem={args.mem}")

    return "\n".join(out)


def _run_script(seed: int, args: argparse.Namespace) -> str:
    return f"""
set -euo pipefail

MODE="${{1:-both}}"  # train | frozen | both
case "$MODE" in
  train|frozen|both) ;;
  *)
    echo "Usage: $0 [train|frozen|both]"
    exit 2
    ;;
esac

REPO_ROOT="{args.repo_root}"
SCR="{args.scratch_root}"
SEED="{seed}"

RUN_STEPS="${{RUN_STEPS:-{args.run_steps}}}"
ARM_TIMEOUT="${{ARM_TIMEOUT:-{args.arm_timeout}}}"
SPEC_TOKENS="${{SPEC_TOKENS:-{args.spec_tokens}}}"
TRAIN_LR="${{TRAIN_LR:-{args.train_lr}}}"
FROZEN_LR="${{FROZEN_LR:-0.0}}"
MAX_EPOCHS="${{MAX_EPOCHS:-{args.max_epochs}}}"
PROMPTS_PER_STEP="${{PROMPTS_PER_STEP:-{args.prompts_per_step}}}"
GENERATIONS_PER_PROMPT="${{GENERATIONS_PER_PROMPT:-{args.generations_per_prompt}}}"
GEN_TEMPERATURE="${{GEN_TEMPERATURE:-{args.temperature}}}"
RATIO_CLIP="${{RATIO_CLIP:-{args.ratio_clip}}}"
REF_KL="${{REF_KL:-{args.ref_kl}}}"
MAX_GRAD_NORM="${{MAX_GRAD_NORM:-{args.max_grad_norm}}}"
SAVE_PERIOD="${{SAVE_PERIOD:-{args.save_period}}}"
CKPT_SIZE_GIB="${{CKPT_SIZE_GIB:-368}}"
SPACE_RESERVE_GIB="${{SPACE_RESERVE_GIB:-300}}"
CONCURRENT_TRAIN_JOBS="${{CONCURRENT_TRAIN_JOBS:-{args.num_seeds}}}"
CKPT_KEEP_TOP_K="${{CKPT_KEEP_TOP_K:-6}}"

TARGET_MODEL="{args.target_model}"
EAGLE_MODEL="{args.eagle_model}"
DATASET_NAME="${{DATASET_NAME:-OpenMathInstruct-2}}"
DATASET_SPLIT="${{DATASET_SPLIT:-{args.dataset_split}}}"
BASE_CFG="{args.base_config}"

export HOME="$SCR"
export PATH="$REPO_ROOT/.venv/bin:$SCR/.local/bin:$PATH"
export VIRTUAL_ENV="$REPO_ROOT/.venv"

if [[ ! -x "$REPO_ROOT/.venv/bin/python" ]]; then
  mkdir -p "$SCR/logs"
  echo "Project .venv missing at $REPO_ROOT/.venv. Bootstrapping with uv sync..." | tee -a "$SCR/logs/eagle_tardrift_preflight.err"
  if ! command -v uv >/dev/null 2>&1; then
    echo "ERROR: uv is not available, cannot create $REPO_ROOT/.venv" | tee -a "$SCR/logs/eagle_tardrift_preflight.err"
    exit 6
  fi
  (
    cd "$REPO_ROOT"
    uv sync --locked --extra vllm --extra fsdp --extra mcore --extra automodel
  ) || {
    echo "ERROR: uv sync failed while creating $REPO_ROOT/.venv" | tee -a "$SCR/logs/eagle_tardrift_preflight.err"
    exit 7
  }
fi

export TMPDIR="$SCR/t"
export TMP="$SCR/t"
export TEMP="$SCR/t"
export UV_CACHE_DIR="$SCR/.cache/uv"
export XDG_CACHE_HOME="$SCR/.cache"
export VLLM_CACHE_ROOT="$SCR/.cache/vllm"
export HF_HOME="$SCR/.cache/hf_user"
export HF_HUB_CACHE="$SCR/.cache/hf_user/hub"
export HUGGINGFACE_HUB_CACHE="$SCR/.cache/hf_user/hub"
export TRANSFORMERS_CACHE="$SCR/.cache/hf_user/hub"
export HF_DATASETS_CACHE="$SCR/.cache/hf_json_cache"
export HF_HUB_OFFLINE="${{HF_HUB_OFFLINE:-1}}"
export HF_DATASETS_OFFLINE="${{HF_DATASETS_OFFLINE:-1}}"

export RAY_TMPDIR="$SCR/t/ray"
export RAY_ENABLE_UV_RUN_RUNTIME_ENV="${{RAY_ENABLE_UV_RUN_RUNTIME_ENV:-0}}"
export VLLM_LOG_STATS_INTERVAL=1
export PYTHONUNBUFFERED=1
export NRL_FORCE_LOCAL_RAY=true
export NEMO_RL_PY_EXECUTABLES_SYSTEM="${{NEMO_RL_PY_EXECUTABLES_SYSTEM:-1}}"
export NRL_FORCE_REBUILD_VENVS="${{NRL_FORCE_REBUILD_VENVS:-false}}"
export VLLM_DISABLE_COMPILE_CACHE=1
export VENV_NAMESPACE="${{VENV_NAMESPACE:-eagle-tardrift-seed${{SEED}}-job${{SLURM_JOB_ID:-manual}}}}"
export NEMO_RL_VENV_DIR="${{NEMO_RL_VENV_DIR:-$SCR/venvs/${{VENV_NAMESPACE}}}}"
export POLICY_PY="${{POLICY_PY:-$REPO_ROOT/.venv/bin/python}}"
export PRECHECK_TIMEOUT_SECONDS="${{PRECHECK_TIMEOUT_SECONDS:-180}}"

# Best-effort CUDA toolkit discovery for any runtime env rebuild path that compiles extensions.
if [[ -z "${{CUDA_HOME:-}}" ]]; then
  if command -v nvcc >/dev/null 2>&1; then
    CUDA_HOME="$(dirname "$(dirname "$(readlink -f "$(command -v nvcc)")")")"
  elif [[ -d /usr/local/cuda ]]; then
    CUDA_HOME="/usr/local/cuda"
  elif compgen -G "/usr/local/cuda-*" >/dev/null; then
    CUDA_HOME="$(ls -d /usr/local/cuda-* | sort -V | tail -n 1)"
  fi
  if [[ -n "${{CUDA_HOME:-}}" ]]; then
    export CUDA_HOME
  fi
fi
if [[ -n "${{CUDA_HOME:-}}" ]]; then
  export PATH="$CUDA_HOME/bin:$PATH"
  export LD_LIBRARY_PATH="$CUDA_HOME/lib64:${{LD_LIBRARY_PATH:-}}"
fi

mkdir -p "$SCR/t" "$SCR/logs" "$SCR/results" \
  "$UV_CACHE_DIR" "$XDG_CACHE_HOME" "$VLLM_CACHE_ROOT" "$NEMO_RL_VENV_DIR" \
  "$HF_HUB_CACHE" "$HF_DATASETS_CACHE" "$RAY_TMPDIR"

# Clear stale build markers to avoid deadlock in nemo_rl.utils.venvs._env_builder.
if [[ -d "$NEMO_RL_VENV_DIR" ]]; then
  while IFS= read -r started_file; do
    venv_dir="$(dirname "$started_file")"
    if [[ ! -x "$venv_dir/bin/python" ]]; then
      echo "Removing stale STARTED_ENV_BUILDER marker: $started_file"
      rm -f "$started_file"
    fi
  done < <(find "$NEMO_RL_VENV_DIR" -maxdepth 2 -type f -name STARTED_ENV_BUILDER 2>/dev/null || true)
fi

if [[ "$NEMO_RL_PY_EXECUTABLES_SYSTEM" == "1" ]]; then
  if [[ ! -x "$POLICY_PY" ]]; then
    echo "ERROR: POLICY_PY is not executable: $POLICY_PY" | tee -a "$SCR/logs/eagle_tardrift_preflight.err"
    exit 5
  fi

  # A broken transformer-engine meta package in the policy env causes worker import stalls/failures.
  if ! "$POLICY_PY" - <<'PY' >/dev/null 2>&1
import importlib.util

if importlib.util.find_spec("transformer_engine") is None:
    raise SystemExit(0)
try:
    import transformer_engine.pytorch  # noqa: F401
except Exception:
    raise SystemExit(1)
raise SystemExit(0)
PY
  then
    echo "WARN: Broken transformer-engine detected in POLICY_PY env; uninstalling it for this run." | tee -a "$SCR/logs/eagle_tardrift_preflight.err"
    "$POLICY_PY" -m pip uninstall -y transformer-engine transformer_engine >/dev/null 2>&1 || true
  fi

  set +e
  timeout "$PRECHECK_TIMEOUT_SECONDS" "$POLICY_PY" - <<'PY' >/dev/null 2>&1
import torch  # noqa: F401
import vllm  # noqa: F401
import vllm._C  # noqa: F401
try:
    # Older torch path
    from torch.distributed.tensor import register_op_strategy  # noqa: F401
except ImportError:
    # Newer torch path
    from torch.distributed.tensor._ops.utils import register_op_strategy  # noqa: F401
import nemo_automodel.components._peft.module_matcher  # noqa: F401
PY
  preflight_rc=$?
  set -e
  if [[ "$preflight_rc" -ne 0 ]]; then
    if [[ "$preflight_rc" -eq 124 ]]; then
      echo "ERROR: POLICY_PY preflight timed out after ${PRECHECK_TIMEOUT_SECONDS}s." | tee -a "$SCR/logs/eagle_tardrift_preflight.err"
      echo "Likely stuck importing nemo_automodel module_matcher / transformer-engine path." | tee -a "$SCR/logs/eagle_tardrift_preflight.err"
    else
      echo "ERROR: POLICY_PY preflight import check failed (torch/vLLM/DTensor/module_matcher), likely env mismatch." | tee -a "$SCR/logs/eagle_tardrift_preflight.err"
    fi
    if command -v nvcc >/dev/null 2>&1 || [[ -n "${{CUDA_HOME:-}}" ]]; then
      echo "Try re-submitting with:" | tee -a "$SCR/logs/eagle_tardrift_preflight.err"
      echo "  --export=ALL,NEMO_RL_PY_EXECUTABLES_SYSTEM=0,RAY_ENABLE_UV_RUN_RUNTIME_ENV=1,NRL_FORCE_REBUILD_VENVS=true" | tee -a "$SCR/logs/eagle_tardrift_preflight.err"
    else
      echo "This node has no CUDA toolkit (nvcc/CUDA_HOME), so runtime venv rebuild will fail." | tee -a "$SCR/logs/eagle_tardrift_preflight.err"
      echo "Fix the frozen env on login node (install a torch-compatible vLLM wheel), then resubmit in system mode." | tee -a "$SCR/logs/eagle_tardrift_preflight.err"
    fi
    exit 3
  fi
fi

if [[ "$NEMO_RL_PY_EXECUTABLES_SYSTEM" == "0" || "$NRL_FORCE_REBUILD_VENVS" == "true" ]]; then
  if ! command -v nvcc >/dev/null 2>&1 && [[ -z "${{CUDA_HOME:-}}" ]]; then
    echo "ERROR: runtime-env rebuild requested, but nvcc/CUDA_HOME is unavailable on this node." | tee -a "$SCR/logs/eagle_tardrift_preflight.err"
    echo "This cluster shape cannot build deep-ep from source without CUDA toolkit." | tee -a "$SCR/logs/eagle_tardrift_preflight.err"
    echo "Use a node image with CUDA toolkit, or switch back to frozen/system mode with a compatible .venv." | tee -a "$SCR/logs/eagle_tardrift_preflight.err"
    exit 4
  fi
fi

cd "$REPO_ROOT"

EXP_TS="$(date +%F-%H%M%S)"
EXP_ROOT="$SCR/logs/{args.tag_prefix}-seed${{SEED}}-s${{SPEC_TOKENS}}-steps${{RUN_STEPS}}-${{EXP_TS}}"
EXP_RESULTS_ROOT="$SCR/results/{args.tag_prefix}-seed${{SEED}}-s${{SPEC_TOKENS}}-steps${{RUN_STEPS}}-${{EXP_TS}}"
mkdir -p "$EXP_ROOT" "$EXP_RESULTS_ROOT"

LOCAL_CFG="$SCR/t/grpo-qwen3-32b-eagle3-lowbatch.${{EXP_TS}}.seed${{SEED}}.local.yaml"
cp "$BASE_CFG" "$LOCAL_CFG"
sed -i "s#^defaults: /opt/nemo-rl/examples/configs/grpo_math_1B.yaml#defaults: $REPO_ROOT/examples/configs/grpo_math_1B.yaml#" "$LOCAL_CFG"

STATUS="$EXP_ROOT/status.log"
{{
  echo "$(date '+%F %T %Z') START mode=${{MODE}} seed=${{SEED}} steps=${{RUN_STEPS}} spec_tokens=${{SPEC_TOKENS}}"
  echo "$(date '+%F %T %Z') profile=reasonable train_lr=${{TRAIN_LR}} frozen_lr=${{FROZEN_LR}} max_epochs=${{MAX_EPOCHS}}"
  echo "$(date '+%F %T %Z') clip=${{RATIO_CLIP}} ref_kl=${{REF_KL}} max_grad_norm=${{MAX_GRAD_NORM}} temp=${{GEN_TEMPERATURE}}"
  echo "$(date '+%F %T %Z') dataset_name=${{DATASET_NAME}} split=${{DATASET_SPLIT}}"
  echo "exp_root=${{EXP_ROOT}}"
  echo "exp_results_root=${{EXP_RESULTS_ROOT}}"
  echo "local_cfg=${{LOCAL_CFG}}"
  echo "nemo_rl_venv_dir=${{NEMO_RL_VENV_DIR}}"
  echo "policy_py=${{POLICY_PY}}"
  echo "nemo_rl_py_executables_system=${{NEMO_RL_PY_EXECUTABLES_SYSTEM}} nrl_force_rebuild_venvs=${{NRL_FORCE_REBUILD_VENVS}}"
  echo "hf_hub_offline=${{HF_HUB_OFFLINE}} hf_datasets_offline=${{HF_DATASETS_OFFLINE}}"
  echo "cuda_home=${{CUDA_HOME:-unset}}"
}} | tee "$STATUS"

run_arm() {{
  local arm="$1"
  local lr="$2"
  local ckpt_enabled="true"
  local ckpt_save_period="$SAVE_PERIOD"
  local ckpt_keep_top_k="$CKPT_KEEP_TOP_K"
  local avail_gib=""
  local safe_ckpts_per_job=""
  if [[ "$arm" == "frozen" ]]; then
    ckpt_enabled="false"
  else
    avail_gib=$(df --output=avail -BG "$SCR" | tail -1 | tr -cd '0-9')
    local ckpt_size_gib="$CKPT_SIZE_GIB"
    local reserve_gib="$SPACE_RESERVE_GIB"
    local concurrent_jobs="$CONCURRENT_TRAIN_JOBS"

    if [[ ! "$avail_gib" =~ ^[0-9]+$ ]]; then
      avail_gib=0
    fi
    if [[ ! "$ckpt_size_gib" =~ ^[0-9]+$ || "$ckpt_size_gib" -le 0 ]]; then
      ckpt_size_gib=368
    fi
    if [[ ! "$reserve_gib" =~ ^[0-9]+$ || "$reserve_gib" -lt 0 ]]; then
      reserve_gib=300
    fi
    if [[ ! "$concurrent_jobs" =~ ^[0-9]+$ || "$concurrent_jobs" -le 0 ]]; then
      concurrent_jobs=1
    fi
    if [[ ! "$ckpt_save_period" =~ ^[0-9]+$ || "$ckpt_save_period" -le 0 ]]; then
      ckpt_save_period=50
    fi
    if [[ ! "$ckpt_keep_top_k" =~ ^[0-9]+$ || "$ckpt_keep_top_k" -le 0 ]]; then
      ckpt_keep_top_k=1
    fi

    local usable_gib=$((avail_gib - reserve_gib))
    if (( usable_gib < 0 )); then
      usable_gib=0
    fi

    local max_total_ckpts=$((usable_gib / ckpt_size_gib))
    safe_ckpts_per_job=$((max_total_ckpts / concurrent_jobs))
    if (( safe_ckpts_per_job < 1 )); then
      safe_ckpts_per_job=1
    fi

    local min_save_period=$(((RUN_STEPS + safe_ckpts_per_job - 1) / safe_ckpts_per_job))
    if (( min_save_period < 1 )); then
      min_save_period=1
    fi
    if (( ckpt_save_period < min_save_period )); then
      ckpt_save_period="$min_save_period"
    fi
    if (( ckpt_keep_top_k > safe_ckpts_per_job )); then
      ckpt_keep_top_k="$safe_ckpts_per_job"
    fi
  fi

  local run_tag="{args.tag_prefix}-eagle3-s${{SPEC_TOKENS}}-seed${{SEED}}-${{arm}}-steps${{RUN_STEPS}}-${{EXP_TS}}"
  local logroot="$SCR/logs/${{run_tag}}"
  local resroot="$SCR/results/${{run_tag}}"
  local run_log="$logroot/run-${{RUN_STEPS}}steps-seed${{SEED}}-${{arm}}-eagle3.log"

  mkdir -p "$logroot"
  if [[ "$ckpt_enabled" == "true" ]]; then
    mkdir -p "$resroot"
  fi
  echo "$(date '+%F %T %Z') seed=${{SEED}} arm=${{arm}} lr=${{lr}} ckpt_enabled=${{ckpt_enabled}} ckpt_save_period=${{ckpt_save_period}} ckpt_keep_top_k=${{ckpt_keep_top_k}} safe_ckpts_per_job=${{safe_ckpts_per_job:-n/a}} avail_gib=${{avail_gib:-n/a}} logroot=${{logroot}}" | tee -a "$STATUS"

  .venv/bin/ray stop --force || true

  timeout "$ARM_TIMEOUT" stdbuf -oL -eL .venv/bin/python - \
    --config "$LOCAL_CFG" \
    "++grpo.max_num_steps=${{RUN_STEPS}}" \
    "++grpo.max_num_epochs=${{MAX_EPOCHS}}" \
    "++grpo.val_period=0" \
    "++grpo.val_at_start=false" \
    "++grpo.val_at_end=false" \
    "++grpo.seed=${{SEED}}" \
    "++grpo.num_prompts_per_step=${{PROMPTS_PER_STEP}}" \
    "++grpo.num_generations_per_prompt=${{GENERATIONS_PER_PROMPT}}" \
    "++policy.dtensor_cfg.activation_checkpointing=true" \
    "++policy.model_name=${{TARGET_MODEL}}" \
    "++policy.tokenizer.name=${{TARGET_MODEL}}" \
    "++policy.max_total_sequence_length=5120" \
    "++policy.generation.max_new_tokens=4096" \
    "++policy.generation.temperature=${{GEN_TEMPERATURE}}" \
    "++policy.generation.top_p=1.0" \
    "++policy.generation.top_k=null" \
    "++policy.generation.vllm_cfg.load_format=auto" \
    "++policy.generation.vllm_cfg.max_model_len=5120" \
    "++policy.generation.vllm_kwargs.attention_backend=FLASH_ATTN" \
    "++policy.generation.vllm_kwargs.speculative_config.model=${{EAGLE_MODEL}}" \
    "++policy.generation.vllm_kwargs.speculative_config.method=eagle3" \
    "++policy.generation.vllm_kwargs.speculative_config.num_speculative_tokens=${{SPEC_TOKENS}}" \
    "++policy.generation.vllm_kwargs.speculative_config.draft_tensor_parallel_size=1" \
    "++policy.optimizer.kwargs.lr=${{lr}}" \
    "++policy.max_grad_norm=${{MAX_GRAD_NORM}}" \
    "++loss_fn.ratio_clip_min=${{RATIO_CLIP}}" \
    "++loss_fn.ratio_clip_max=${{RATIO_CLIP}}" \
    "++loss_fn.reference_policy_kl_penalty=${{REF_KL}}" \
    "++cluster.gpus_per_node={args.cluster_gpus_per_node}" \
    "++cluster.num_nodes={args.cluster_num_nodes}" \
    "++env.math.num_workers=1" \
    "++data.train.dataset_name=${{DATASET_NAME}}" \
    "++data.train.split=${{DATASET_SPLIT}}" \
    "++data.train.split_validation_size=0.0" \
    "++data.validation=null" \
    "++data.default.dataset_name=${{DATASET_NAME}}" \
    "++data.default.processor=math_hf_data_processor" \
    "++data.default.env_name=math" \
    "++data.default.prompt_file=examples/prompts/cot.txt" \
    "++logger.log_dir=${{logroot}}" \
    "++checkpointing.enabled=${{ckpt_enabled}}" \
    "++checkpointing.save_period=${{ckpt_save_period}}" \
    "++checkpointing.keep_top_k=${{ckpt_keep_top_k}}" \
    "++checkpointing.checkpoint_dir=${{resroot}}" \
    <<'PY' 2>&1 | tee "$run_log"
import os
import runpy
import sys

from nemo_rl.distributed.ray_actor_environment_registry import ACTOR_ENVIRONMENT_REGISTRY

policy_py = os.environ.get("POLICY_PY")
if policy_py:
    ACTOR_ENVIRONMENT_REGISTRY[
        "nemo_rl.models.policy.workers.dtensor_policy_worker_v2.DTensorPolicyWorkerV2"
    ] = policy_py
    ACTOR_ENVIRONMENT_REGISTRY[
        "nemo_rl.models.policy.workers.dtensor_policy_worker.DTensorPolicyWorker"
    ] = policy_py

sys.argv = ["examples/run_grpo.py", *sys.argv[1:]]
runpy.run_path("examples/run_grpo.py", run_name="__main__")
PY

  local rc=${{PIPESTATUS[0]}}
  echo "$(date '+%F %T %Z') seed=${{SEED}} arm=${{arm}} rc=${{rc}} run_log=${{run_log}}" | tee -a "$STATUS"
  return "$rc"
}}

case "$MODE" in
  train)
    run_arm train "$TRAIN_LR"
    ;;
  frozen)
    run_arm frozen "$FROZEN_LR"
    ;;
  both)
    run_arm train "$TRAIN_LR"
    run_arm frozen "$FROZEN_LR"
    ;;
esac

echo "$(date '+%F %T %Z') DONE mode=${{MODE}} seed=${{SEED}} exp_root=${{EXP_ROOT}}" | tee -a "$STATUS"
""".lstrip()


def _submit_all(scripts: Iterable[Path]) -> str:
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        'cd "$(dirname "$0")"',
        "",
        'extra=()',
        'if [[ -n "${SBATCH_EXTRA_ARGS:-}" ]]; then',
        "  # shellcheck disable=SC2206",
        '  extra=(${SBATCH_EXTRA_ARGS})',
        "fi",
        "",
        'export_vars="${SBATCH_EXPORT_VARS:-ALL,NEMO_RL_PY_EXECUTABLES_SYSTEM=1,NRL_FORCE_REBUILD_VENVS=false,RAY_ENABLE_UV_RUN_RUNTIME_ENV=0}"',
        "",
        "echo \"Submitting all seed jobs...\"",
    ]
    for script in scripts:
        lines.append(
            f'job_id=$(sbatch --parsable "${{extra[@]}}" --export="${{export_vars}}" "{script.name}")'
        )
        lines.append(f'echo "submitted {script.name} -> $job_id"')
    lines.append('echo "Done."')
    lines.append("")
    return "\n".join(lines)


def _submit_train_all(scripts: Iterable[Path]) -> str:
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        'cd "$(dirname "$0")"',
        "",
        'extra=()',
        'if [[ -n "${SBATCH_EXTRA_ARGS:-}" ]]; then',
        "  # shellcheck disable=SC2206",
        '  extra=(${SBATCH_EXTRA_ARGS})',
        "fi",
        "",
        'export_vars="${SBATCH_EXPORT_VARS:-ALL,NEMO_RL_PY_EXECUTABLES_SYSTEM=1,NRL_FORCE_REBUILD_VENVS=false,RAY_ENABLE_UV_RUN_RUNTIME_ENV=0}"',
        "",
        "echo \"Submitting TRAIN phase for all seeds...\"",
    ]
    for script in scripts:
        lines.append(
            f'job_id=$(sbatch --parsable "${{extra[@]}}" --export="${{export_vars}}" "{script.name}" train)'
        )
        lines.append(f'echo "train {script.name} -> $job_id"')
    lines.append('echo "Done."')
    lines.append("")
    return "\n".join(lines)


def _submit_frozen_all(scripts: Iterable[Path]) -> str:
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        'cd "$(dirname "$0")"',
        "",
        'extra=()',
        'if [[ -n "${SBATCH_EXTRA_ARGS:-}" ]]; then',
        "  # shellcheck disable=SC2206",
        '  extra=(${SBATCH_EXTRA_ARGS})',
        "fi",
        "",
        'export_vars="${SBATCH_EXPORT_VARS:-ALL,NEMO_RL_PY_EXECUTABLES_SYSTEM=1,NRL_FORCE_REBUILD_VENVS=false,RAY_ENABLE_UV_RUN_RUNTIME_ENV=0}"',
        "",
        "echo \"Submitting FROZEN phase for all seeds...\"",
    ]
    for script in scripts:
        lines.append(
            f'job_id=$(sbatch --parsable "${{extra[@]}}" --export="${{export_vars}}" "{script.name}" frozen)'
        )
        lines.append(f'echo "frozen {script.name} -> $job_id"')
    lines.append('echo "Done."')
    lines.append("")
    return "\n".join(lines)


def _submit_trains_then_frozen(scripts: Iterable[Path]) -> str:
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        'cd "$(dirname "$0")"',
        "",
        '# Dependency type for frozen phase: "afterany" (default) or "afterok"',
        'DEP_TYPE="${DEP_TYPE:-afterany}"',
        'if [[ "$DEP_TYPE" != "afterany" && "$DEP_TYPE" != "afterok" ]]; then',
        '  echo "DEP_TYPE must be afterany or afterok" >&2',
        "  exit 2",
        "fi",
        "",
        'extra=()',
        'if [[ -n "${SBATCH_EXTRA_ARGS:-}" ]]; then',
        "  # shellcheck disable=SC2206",
        '  extra=(${SBATCH_EXTRA_ARGS})',
        "fi",
        "",
        'export_vars="${SBATCH_EXPORT_VARS:-ALL,NEMO_RL_PY_EXECUTABLES_SYSTEM=1,NRL_FORCE_REBUILD_VENVS=false,RAY_ENABLE_UV_RUN_RUNTIME_ENV=0}"',
        "",
        "echo \"Submitting TRAIN phase for all seeds...\"",
        "declare -a train_ids=()",
    ]
    for script in scripts:
        lines.append(
            f'jid=$(sbatch --parsable "${{extra[@]}}" --export="${{export_vars}}" "{script.name}" train)'
        )
        lines.append("train_ids+=(\"$jid\")")
        lines.append(f'echo "train {script.name} -> $jid"')
    lines.extend(
        [
            'dep=$(IFS=:; echo "${train_ids[*]}")',
            'echo "Submitting FROZEN phase for all seeds with dependency ${DEP_TYPE}:${dep}"',
        ]
    )
    for script in scripts:
        lines.append(
            f'jid=$(sbatch --parsable "${{extra[@]}}" --export="${{export_vars}}" --dependency="${{DEP_TYPE}}:${{dep}}" "{script.name}" frozen)'
        )
        lines.append(f'echo "frozen {script.name} -> $jid (dep ${{DEP_TYPE}}:${{dep}})"')
    lines.append('echo "Done."')
    lines.append("")
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate Slurm submit scripts for 5-seed TAR-drift testing with "
            "EAGLE3 under reasonable GRPO settings."
        )
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("/home/scratch.shaunakj_other/Development/RL/slurm_submits"),
        help="Directory where generated .sbatch scripts are written.",
    )
    parser.add_argument(
        "--seeds",
        type=str,
        default="123,124,125,126,127",
        help="Comma-separated seeds.",
    )
    parser.add_argument("--job-prefix", type=str, default="eagle-tardrift")

    # Slurm knobs
    parser.add_argument("--nodes", type=int, default=1)
    parser.add_argument("--cpus-per-task", type=int, default=64)
    parser.add_argument("--time-limit", type=str, default="04:00:00")
    parser.add_argument("--partition", type=str, default="")
    parser.add_argument("--account", type=str, default="")
    parser.add_argument("--qos", type=str, default="")
    parser.add_argument("--constraint", type=str, default="")
    parser.add_argument("--gres", type=str, default="gpu:8")
    parser.add_argument("--mem", type=str, default="")
    parser.add_argument(
        "--slurm-log-dir",
        type=str,
        default="/home/scratch.shaunakj_other/logs",
        help="Path used in #SBATCH --output/--error.",
    )

    # GRPO profile knobs (reasonable defaults)
    parser.add_argument("--run-steps", type=int, default=135)
    parser.add_argument("--arm-timeout", type=str, default="230m")
    parser.add_argument("--spec-tokens", type=int, default=4)
    parser.add_argument("--train-lr", type=float, default=5e-6)
    parser.add_argument("--max-epochs", type=int, default=1)
    parser.add_argument("--prompts-per-step", type=int, default=2)
    parser.add_argument("--generations-per-prompt", type=int, default=8)
    parser.add_argument("--temperature", type=float, default=0.6)
    parser.add_argument("--ratio-clip", type=float, default=0.2)
    parser.add_argument("--ref-kl", type=float, default=0.01)
    parser.add_argument("--max-grad-norm", type=float, default=1.0)
    parser.add_argument("--save-period", type=int, default=50)

    # Cluster/runtime/model knobs
    parser.add_argument("--repo-root", type=str, default="/home/scratch.shaunakj_other/Development/RL")
    parser.add_argument("--scratch-root", type=str, default="/home/scratch.shaunakj_other")
    parser.add_argument("--cluster-gpus-per-node", type=int, default=8)
    parser.add_argument("--cluster-num-nodes", type=int, default=1)
    parser.add_argument(
        "--base-config",
        type=str,
        default=(
            "/home/scratch.shaunakj_other/Development/RL/examples/configs/recipes/llm/"
            "grpo-qwen3-32b-spec-decode-lowbatch-1n8g.yaml"
        ),
    )
    parser.add_argument(
        "--dataset-split",
        type=str,
        default="train",
        choices=["train", "train_1M", "train_2M", "train_5M"],
        help="OpenMathInstruct-2 split to use for training.",
    )
    parser.add_argument(
        "--target-model",
        type=str,
        default=(
            "/home/scratch.shaunakj_other/.cache/huggingface/hub/models--Qwen--Qwen3-32B/"
            "snapshots/9216db5781bf21249d130ec9da846c4624c16137"
        ),
    )
    parser.add_argument(
        "--eagle-model",
        type=str,
        default=(
            "/home/scratch.shaunakj_other/.cache/hf_user/hub/"
            "models--RedHatAI--Qwen3-32B-speculator.eagle3/"
            "snapshots/e5756763c9b3bef3cc260cab70b76008fb42a81b"
        ),
    )
    parser.add_argument(
        "--tag-prefix",
        type=str,
        default="tar-drift-reasonable",
        help="Prefix used for run log/result directories.",
    )

    return parser.parse_args()


def main() -> None:
    args = parse_args()
    seeds = _csv_ints(args.seeds)
    args.num_seeds = len(seeds)

    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    out_dir = args.output_dir / f"generated-{timestamp}"
    out_dir.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []
    for seed in seeds:
        script_path = out_dir / f"submit_eagle_tardrift_seed{seed}.sbatch"
        content = _slurm_header(seed, args) + "\n\n" + _run_script(seed, args)
        script_path.write_text(content)
        script_path.chmod(0o755)
        written.append(script_path)

    submit_all = out_dir / "submit_all.sh"
    submit_all.write_text(_submit_all(written))
    submit_all.chmod(0o755)

    submit_train_all = out_dir / "submit_train_all.sh"
    submit_train_all.write_text(_submit_train_all(written))
    submit_train_all.chmod(0o755)

    # Backward-compatible alias for workflows that expect submit_train.sh.
    submit_train = out_dir / "submit_train.sh"
    submit_train.write_text(_submit_train_all(written))
    submit_train.chmod(0o755)

    submit_frozen_all = out_dir / "submit_frozen_all.sh"
    submit_frozen_all.write_text(_submit_frozen_all(written))
    submit_frozen_all.chmod(0o755)

    submit_trains_then_frozen = out_dir / "submit_trains_then_frozen.sh"
    submit_trains_then_frozen.write_text(_submit_trains_then_frozen(written))
    submit_trains_then_frozen.chmod(0o755)

    print(f"Wrote {len(written)} seed scripts to: {out_dir}")
    for path in written:
        print(f" - {path}")
    print(f" - {submit_all}")
    print(f" - {submit_train_all}")
    print(f" - {submit_train}")
    print(f" - {submit_frozen_all}")
    print(f" - {submit_trains_then_frozen}")


if __name__ == "__main__":
    main()
