#!/usr/bin/env python3
"""Convert parameter-tool SFT rows into a small NeMo-Gym rollout dataset."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any, Iterable


DEFAULT_INPUT = Path(
    "/lustre/fsw/portfolios/llmservice/users/smohsenitahe/"
    "tool_calls_gen/sft_final/train.jsonl"
)
IMAGE_TOOL_NAMES = frozenset(
    {
        "image_zoom_in_tool",
        "image_crop_tool",
        "image_rotate_tool",
        "image_flip_tool",
        "image_diff_tool",
        "image_side_by_side_tool",
        "image_overlay_tool",
        "count_objects_tool",
        "find_color_tool",
        "color_at_tool",
    }
)
IMAGE_TOOLS_AGENT_REF = {
    "type": "responses_api_agents",
    "name": "image_tools_simple_agent",
}
STRING_MATCH_AGENT_REF = {
    "type": "responses_api_agents",
    "name": "string_match_simple_agent",
}
_FUNCTION_RE = re.compile(r"<function=([^>\s]+)>")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument(
        "--cover-all-tools",
        action="store_true",
        help="Select a greedy, deterministic set of rows covering all ten tools.",
    )
    parser.add_argument(
        "--scan-limit",
        type=int,
        default=1000,
        help="Maximum source rows inspected for --cover-all-tools.",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=4,
        help="Number of leading rows to convert when not selecting tool coverage.",
    )
    parser.add_argument(
        "--allow-missing-images",
        action="store_true",
        help="Keep unresolved image paths instead of failing conversion.",
    )
    return parser.parse_args()


def extract_tool_names(row: dict[str, Any]) -> frozenset[str]:
    names: set[str] = set()
    for turn in row.get("conversations", []):
        if turn.get("from") != "gpt":
            continue
        names.update(_FUNCTION_RE.findall(str(turn.get("value", ""))))
    return frozenset(names & IMAGE_TOOL_NAMES)


def _initial_turn(row: dict[str, Any], role: str) -> str:
    for turn in row.get("conversations", []):
        if turn.get("from") == role:
            return str(turn.get("value", ""))
    raise ValueError(f"Row {row.get('id')!r} is missing an initial {role!r} turn")


def _resolve_image_paths(
    row: dict[str, Any], *, image_count: int, allow_missing_images: bool
) -> list[str]:
    metadata = row.get("__metadata__") or {}
    media_root = metadata.get("media_root")
    if not media_root:
        raise ValueError(f"Row {row.get('id')!r} is missing __metadata__.media_root")
    if image_count < 1:
        raise ValueError(f"Row {row.get('id')!r} has no initial <image> anchors")
    image_values = list(row.get("image", []))
    if len(image_values) < image_count:
        raise ValueError(
            f"Row {row.get('id')!r} has {image_count} initial image anchors but only "
            f"{len(image_values)} image paths"
        )
    # The top-level SFT image list also contains images produced by later tool
    # turns. Only the leading images referenced by the initial human turn belong
    # in the rollout prompt; tool outputs must be regenerated by the environment.
    paths = [
        (Path(media_root) / relative).resolve()
        for relative in image_values[:image_count]
    ]
    if not paths:
        raise ValueError(f"Row {row.get('id')!r} has no images")
    missing = [path for path in paths if not path.is_file()]
    if missing and not allow_missing_images:
        raise FileNotFoundError(
            f"Row {row.get('id')!r} has missing images: "
            + ", ".join(str(path) for path in missing)
        )
    return [str(path) for path in paths]


def _user_content(text: str, image_paths: list[str]) -> list[dict[str, Any]]:
    """Interleave structured images at the source row's ``<image>`` anchors."""
    content: list[dict[str, Any]] = []
    pieces = text.split("<image>")
    for index, piece in enumerate(pieces):
        if piece:
            content.append({"type": "input_text", "text": piece})
        if index < len(pieces) - 1 and index < len(image_paths):
            content.append(
                {
                    "type": "input_image",
                    "image_url": image_paths[index],
                    "detail": "auto",
                }
            )
    for path in image_paths[max(0, len(pieces) - 1) :]:
        content.append({"type": "input_image", "image_url": path, "detail": "auto"})
    return content


def convert_sft_row(
    row: dict[str, Any], *, allow_missing_images: bool = False
) -> dict[str, Any]:
    metadata = dict(row.get("__metadata__") or {})
    expected_answer = metadata.get("answer")
    if expected_answer is None:
        raise ValueError(f"Row {row.get('id')!r} is missing __metadata__.answer")
    human_turn = _initial_turn(row, "human")
    image_paths = _resolve_image_paths(
        row,
        image_count=human_turn.count("<image>"),
        allow_missing_images=allow_missing_images,
    )
    tool_names = sorted(extract_tool_names(row))
    return {
        "id": row.get("id"),
        "agent_ref": dict(IMAGE_TOOLS_AGENT_REF),
        "image_tools_base_agent_ref": dict(STRING_MATCH_AGENT_REF),
        "expected_answer": str(expected_answer),
        "extraction_mode": "final_answer",
        "responses_create_params": {
            "input": [
                {
                    "role": "system",
                    "type": "message",
                    "content": _initial_turn(row, "system"),
                },
                {
                    "role": "user",
                    "type": "message",
                    "content": _user_content(human_turn, image_paths),
                },
            ],
            "tools": [],
            "parallel_tool_calls": False,
        },
        "dataset": metadata.get("dataset_version", "image_tools_sft"),
        "source_task": metadata.get("task"),
        "source_tool_names": tool_names,
        "source_n_tool_calls": metadata.get("n_tool_calls", 0),
    }


def select_covering_rows(
    rows: Iterable[dict[str, Any]], *, scan_limit: int
) -> list[dict[str, Any]]:
    candidates: list[tuple[int, dict[str, Any], frozenset[str]]] = []
    observed: set[str] = set()
    for index, row in enumerate(rows):
        if index >= scan_limit:
            break
        tools = extract_tool_names(row)
        if tools:
            candidates.append((index, row, tools))
            observed.update(tools)
        if observed >= IMAGE_TOOL_NAMES:
            break
    missing = IMAGE_TOOL_NAMES - observed
    if missing:
        raise ValueError(
            f"Did not observe all image tools in the first {scan_limit} rows; "
            f"missing {sorted(missing)}"
        )

    uncovered = set(IMAGE_TOOL_NAMES)
    selected: list[tuple[int, dict[str, Any], frozenset[str]]] = []
    remaining = list(candidates)
    while uncovered:
        best = max(
            remaining,
            key=lambda candidate: (len(candidate[2] & uncovered), -candidate[0]),
        )
        if not best[2] & uncovered:
            raise AssertionError(f"Unable to cover tools: {sorted(uncovered)}")
        selected.append(best)
        uncovered -= best[2]
        remaining.remove(best)
    selected.sort(key=lambda candidate: candidate[0])
    return [row for _, row, _ in selected]


def main() -> None:
    args = parse_args()
    with args.input.open() as source:
        if args.cover_all_tools:
            selected = select_covering_rows(
                (json.loads(line) for line in source if line.strip()),
                scan_limit=args.scan_limit,
            )
        else:
            selected = []
            for line in source:
                if not line.strip():
                    continue
                selected.append(json.loads(line))
                if len(selected) >= args.limit:
                    break

    converted = [
        convert_sft_row(row, allow_missing_images=args.allow_missing_images)
        for row in selected
    ]
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w") as output:
        for row in converted:
            output.write(
                json.dumps(row, ensure_ascii=False, separators=(",", ":")) + "\n"
            )

    covered = sorted(
        set().union(*(set(row["source_tool_names"]) for row in converted))
        if converted
        else set()
    )
    print(
        json.dumps(
            {
                "input": str(args.input),
                "output": str(args.output),
                "rows": len(converted),
                "covered_tools": covered,
                "all_tools_covered": set(covered) == IMAGE_TOOL_NAMES,
            },
            indent=2,
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
